import { QuizQuestion } from "@/models/types";

// Contenu réel (estimated: false) — Chapitre 1 "Les bases du droit"
// (support de cours PGD IG 25/26) et Wooclap "IG - Les bases du droit - 2025".
// Pour ajouter une question : copie un bloc, change l'id, et garde
// correctIndex cohérent avec l'ordre de `choices` (le mélange est fait
// automatiquement à l'affichage, pas besoin d'y penser ici).

const themeId = "bases-du-droit";

export const quizBasesDuDroit: QuizQuestion[] = [
  {
    id: "q-bases-01", themeId,
    question: "Quelle est la meilleure définition du droit objectif ?",
    choices: ["L'ensemble des droits d'une personne", "L'ensemble des règles générales et abstraites imposées par une autorité compétente", "L'ensemble des décisions de justice", "Un ensemble de règles non écrites reconnues par la société"],
    correctIndex: 1,
    explanation: "Le droit objectif est l'ensemble de règles générales et abstraites qui indiquent ce qui doit être fait, édictées ou reconnues par une autorité compétente, et dont le respect est assuré par des moyens de contrainte.",
    estimated: false,
  },
  {
    id: "q-bases-02", themeId,
    question: "La règle de droit est dite « abstraite » car :",
    choices: ["Elle s'applique à une personne spécifique", "Elle est imposée uniquement par l'État", "Elle s'applique à un nombre indéterminé de situations concrètes", "Elle n'a pas de contrainte légale"],
    correctIndex: 2,
    explanation: "Une règle générale et abstraite vise un nombre indéterminé de cas et de personnes, contrairement à une décision individuelle qui vise un cas particulier.",
    estimated: false,
  },
  {
    id: "q-bases-03", themeId,
    question: "Le droit impératif se distingue du droit dispositif car :",
    choices: ["Il peut être modifié par les parties en accord", "Il s'applique uniquement en cas de litige", "Il doit être respecté par tout le monde, sans possibilité de dérogation", "Il est appliqué uniquement dans le domaine du droit pénal"],
    correctIndex: 2,
    explanation: "Le droit impératif (ex. art. 361 CO) ne peut pas être écarté par accord entre les parties, contrairement au droit dispositif (ex. art. 364 al. 3 CO) qui ne s'applique qu'à défaut d'accord contraire.",
    estimated: false,
  },
  {
    id: "q-bases-04", themeId,
    question: "Parmi les sources du droit suivantes, lesquelles sont des sources secondaires ?",
    choices: ["La loi et le règlement", "La jurisprudence et la doctrine", "Uniquement la coutume", "La Constitution fédérale"],
    correctIndex: 1,
    explanation: "La loi est la source primaire du droit suisse. La coutume, la jurisprudence et la doctrine sont des sources secondaires, utilisées notamment en cas de lacune de la loi.",
    estimated: false,
  },
  {
    id: "q-bases-05", themeId,
    question: "Le droit du travail relève-t-il principalement du droit public ou du droit privé ?",
    choices: ["Droit public", "Droit privé", "Les deux, selon le contexte", "Ni l'un ni l'autre"],
    correctIndex: 2,
    explanation: "Le droit du travail relève principalement du droit privé (relation employeur-employé), mais comporte aussi des aspects de droit public (protection des travailleurs, droit public du travail).",
    estimated: false,
  },
  {
    id: "q-bases-06", themeId,
    question: "Selon la hiérarchie des normes en Suisse, quelle norme interne est supérieure aux autres ?",
    choices: ["La loi cantonale", "La Constitution fédérale", "Le règlement communal", "L'ordonnance législative"],
    correctIndex: 1,
    explanation: "Dans la hiérarchie des normes, seul le droit international prime sur la Constitution fédérale, qui est elle-même supérieure aux lois, ordonnances et autres actes internes.",
    estimated: false,
  },
  {
    id: "q-bases-07", themeId,
    question: "Le droit formel (droit de procédure) :",
    choices: ["Définit les droits et obligations des personnes", "Organise la procédure judiciaire", "Règle les relations entre les États", "S'applique uniquement en droit pénal"],
    correctIndex: 1,
    explanation: "Le droit de procédure (ou droit formel) règle la mise en œuvre des droits subjectifs et organise le déroulement des procès ainsi que les voies de recours ; c'est le droit de fond (matériel) qui définit droits et obligations.",
    estimated: false,
  },
  {
    id: "q-bases-08", themeId,
    question: "Quel est le rôle principal du Tribunal fédéral en Suisse ?",
    choices: ["Appliquer les lois cantonales", "Créer de nouvelles lois", "Garantir une application uniforme du droit fédéral", "Gérer les affaires locales"],
    correctIndex: 2,
    explanation: "Le Tribunal fédéral (TF) est la plus haute autorité judiciaire de Suisse ; il garantit une application uniforme du droit fédéral et le respect des droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-bases-09", themeId,
    question: "La jurisprudence est principalement constituée de :",
    choices: ["Décisions rendues par le Parlement", "Décisions rendues par des autorités administratives", "Décisions rendues par les tribunaux", "Lois fédérales"],
    correctIndex: 2,
    explanation: "La jurisprudence est l'ensemble des jugements des tribunaux et des décisions rendues par d'autres autorités investies du pouvoir judiciaire dans un cas d'espèce.",
    estimated: false,
  },
  {
    id: "q-bases-10", themeId,
    question: "Où trouve-t-on la mention des quatre sources du droit suisse ?",
    choices: ["Dans la jurisprudence uniquement", "Dans les traités internationaux", "Dans l'article 1 du Code civil suisse", "Dans l'article 1 du Code des obligations"],
    correctIndex: 2,
    explanation: "L'art. 1 CC mentionne les quatre sources du droit : la loi, la coutume, la jurisprudence et la doctrine.",
    estimated: false,
  },
  {
    id: "q-bases-11", themeId,
    question: "Maxime est arrêté par la police pour conduite en état d'ébriété. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "L'État sanctionne, via le droit pénal, une infraction routière : c'est un rapport vertical entre l'État et un particulier, donc du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-12", themeId,
    question: "Un enseignant renvoie un élève qui adopte un comportement inadéquat en classe. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "L'école est une institution étatique qui exerce une autorité sur l'élève (rapport vertical) : cela relève du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-13", themeId,
    question: "Plusieurs pays ratifient un traité international. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "Un traité entre États règle les relations entre États : cela relève du droit public (droit international public).",
    estimated: false,
  },
  {
    id: "q-bases-14", themeId,
    question: "Par suite du décès de ses parents, Mélanie hérite de leur maison. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 0,
    explanation: "Une succession entre particuliers est un rapport horizontal régi par le droit civil : cela relève du droit privé.",
    estimated: false,
  },
  {
    id: "q-bases-15", themeId,
    question: "Georges doit payer tous les mois son assurance maladie complémentaire. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 0,
    explanation: "L'assurance-maladie complémentaire est un contrat librement conclu avec un assureur privé : cela relève du droit privé, contrairement à l'assurance de base (LAMal) qui relève du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-16", themeId,
    question: "La liberté de la presse est garantie. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "La liberté de la presse est un droit fondamental garanti par la Constitution face à l'État : cela relève du droit public (droit constitutionnel).",
    estimated: false,
  },
  {
    id: "q-bases-17", themeId,
    question: "Les rapports entre individus sont régis en premier lieu, selon l'art. 1 CC, par :",
    choices: ["Le droit public", "Le droit privé", "La coutume", "La jurisprudence"],
    correctIndex: 1,
    explanation: "Les rapports entre particuliers relèvent en premier lieu du droit privé (droit civil, droit des obligations).",
    estimated: false,
  },
  {
    id: "q-bases-18", themeId,
    question: "Une personne privée peut-elle rendre une décision (au sens juridique) ?",
    choices: ["Oui", "Non"],
    correctIndex: 1,
    explanation: "Seule une autorité investie du pouvoir de décision (tribunal, autorité administrative) peut rendre une décision ; un particulier ne le peut pas.",
    estimated: false,
  },
  {
    id: "q-bases-19", themeId,
    question: "Les sources du droit sont, dans l'ordre de l'art. 1 CC :",
    choices: ["Le contrat, la loi, la coutume, l'acte illicite", "L'enrichissement illégitime, la doctrine, la loi, la jurisprudence", "La loi, la coutume, la jurisprudence, la doctrine", "Le contrat, l'enrichissement illégitime, l'acte illicite, la loi"],
    correctIndex: 2,
    explanation: "L'art. 1 CC prévoit, dans cet ordre : la loi (source primaire), puis la coutume, et enfin les solutions consacrées par la doctrine et la jurisprudence.",
    estimated: false,
  },
  {
    id: "q-bases-20", themeId,
    question: "Qui édicte les lois fédérales en Suisse ?",
    choices: ["Les tribunaux", "Le Conseil fédéral", "Le Conseil national et le Conseil d'État", "Le Conseil national et le Conseil des États"],
    correctIndex: 3,
    explanation: "Les lois fédérales sont adoptées par l'Assemblée fédérale, composée du Conseil national et du Conseil des États.",
    estimated: false,
  },
  {
    id: "q-bases-21", themeId,
    question: "Auprès de quel tribunal peut-on porter une affaire si l'on a épuisé toutes les instances en Suisse et que l'on estime que ses droits fondamentaux ont été violés ?",
    choices: ["Le Tribunal fédéral", "Le Tribunal international", "La Cour européenne des droits de l'Homme (CEDH)", "Le Tribunal cantonal de Berne"],
    correctIndex: 2,
    explanation: "Une fois les voies de recours internes épuisées, un recours pour violation des droits fondamentaux peut être porté devant la CEDH.",
    estimated: false,
  },
  {
    id: "q-bases-22", themeId,
    question: "Auprès de quel tribunal porte-t-on une affaire en première instance s'il s'agit d'une infraction visant les intérêts de la Suisse, comme un acte terroriste ?",
    choices: ["Tribunal de police", "Tribunal pénal cantonal", "Tribunal pénal fédéral", "Tribunal fédéral"],
    correctIndex: 2,
    explanation: "Le Tribunal pénal fédéral (TPF), siège à Bellinzone, juge en 1ère instance notamment les infractions visant les intérêts de la Confédération, comme le terrorisme ou le crime organisé.",
    estimated: false,
  },
  {
    id: "q-bases-23", themeId,
    question: "Auprès de quel tribunal porte-t-on une affaire en première instance pour un délit routier mineur ?",
    choices: ["Tribunal pénal fédéral", "Tribunal cantonal", "Tribunal de police", "Tribunal fédéral"],
    correctIndex: 2,
    explanation: "Le tribunal de police, tribunal cantonal de première instance, est compétent pour les délits routiers mineurs.",
    estimated: false,
  },
  {
    id: "q-bases-24", themeId,
    question: "Vers quel tribunal doit-on se tourner en deuxième instance après un jugement du Tribunal de police ?",
    choices: ["Tribunal fédéral", "Tribunal cantonal", "Tribunal administratif fédéral", "Tribunal pénal fédéral"],
    correctIndex: 1,
    explanation: "Le Tribunal cantonal est l'autorité judiciaire cantonale de recours (2e instance) contre les jugements des tribunaux régionaux/de police.",
    estimated: false,
  },
  {
    id: "q-bases-25", themeId,
    question: "Quel tribunal juge en première instance les affaires civiles de faible valeur financière (ex. un litige avec un voisin) ?",
    choices: ["Tribunal régional", "Tribunal administratif fédéral", "Tribunal pénal fédéral", "Tribunal cantonal"],
    correctIndex: 0,
    explanation: "Le tribunal régional (tribunal civil de première instance) juge les litiges civils, y compris de faible valeur, comme un litige de voisinage.",
    estimated: false,
  },
  {
    id: "q-bases-26", themeId,
    question: "Les grandes divisions du droit privé sont :",
    choices: ["Droit administratif, droit civil, droit des obligations et droit commercial", "Droit des obligations, droit de la PI, droit civil et droit pénal", "Droit des obligations, droit de la propriété intellectuelle, droit commercial et droit civil", "Droit pénal, droit civil, droit constitutionnel et droit administratif"],
    correctIndex: 2,
    explanation: "Les grandes divisions du droit privé sont : le droit civil, le droit des obligations, le droit commercial et le droit de la propriété intellectuelle (le droit pénal et le droit administratif relèvent du droit public).",
    estimated: false,
  },
  {
    id: "q-bases-27", themeId,
    question: "Combien de pouvoirs distincts existe-t-il en Suisse (séparation des pouvoirs) ?",
    choices: ["Un", "Deux", "Trois", "Quatre"],
    correctIndex: 2,
    explanation: "La Suisse connaît trois pouvoirs distincts : législatif, exécutif et judiciaire.",
    estimated: false,
  },
  {
    id: "q-bases-28", themeId,
    question: "Où peut-on trouver les textes des lois fédérales en Suisse et comment les consulter ?",
    choices: ["Dans le Registre des sociétés (RS) uniquement", "Dans le Recueil officiel (RO) et le Recueil systématique (RS)", "Dans les journaux locaux", "Dans les archives des cantons uniquement"],
    correctIndex: 1,
    explanation: "Le RO (classé chronologiquement, fait foi) et le RS (classé par domaine, à jour) rassemblent les textes normatifs fédéraux.",
    estimated: false,
  },
  {
    id: "q-bases-29", themeId,
    question: "Qu'est-ce que le droit subjectif ?",
    choices: ["L'ensemble des règles générales et abstraites imposées par une autorité", "Une prérogative accordée à une personne de faire, d'exiger, ou d'être obligée à faire quelque chose", "Uniquement les décisions rendues par les tribunaux", "Uniquement les lois votées par le Parlement"],
    correctIndex: 1,
    explanation: "Le droit subjectif (« mon droit ») est une prérogative accordée à une personne physique ou morale, dictée par le droit objectif ; il se décline en droits, pouvoirs, libertés et obligations.",
    estimated: false,
  },
  {
    id: "q-bases-30", themeId,
    question: "Quelles sont les trois conditions pour qu'une coutume soit reconnue comme source du droit ?",
    choices: ["Être écrite, récente et votée par le peuple", "Être non écrite, née d'un usage durable et implanté, et reconnue par la collectivité comme juridiquement contraignante", "Être approuvée par le Tribunal fédéral, publiée au RO et signée par le Conseil fédéral", "Être appliquée uniquement au niveau international"],
    correctIndex: 1,
    explanation: "La coutume doit être généralement non écrite, être née d'un usage d'une certaine durée qui persiste dans le temps, et être reconnue par la collectivité comme juridiquement obligatoire.",
    estimated: false,
  },
  {
    id: "q-bases-31", themeId,
    question: "Que signifie RO ?",
    choices: ["Recueil officiel : classé par ordre chronologique, la version publiée fait foi", "Recueil des ordonnances classées par matière", "Registre des organisations", "Recueil des opinions de doctrine"],
    correctIndex: 0,
    explanation: "Le RO (Recueil officiel) est classé par ordre chronologique ; c'est la version qui fait foi. Le RS est classé par matière.",
    estimated: false,
  },
  {
    id: "q-bases-32", themeId,
    question: "Le Recueil systématique (RS) est classé :",
    choices: ["Par ordre chronologique", "Par domaine / matière, avec les modifications à jour", "Par canton uniquement", "Par juridiction"],
    correctIndex: 1,
    explanation: "Le RS rassemble dans un ordre systématique (neuf thématiques) les actes en vigueur, avec toutes les modifications jusqu'à la dernière mise à jour.",
    estimated: false,
  },
  {
    id: "q-bases-33", themeId,
    question: "Que représente la FF (Feuille fédérale) ?",
    choices: ["La version de référence des lois en vigueur", "La première publication de la loi, mais on ne se base pas dessus", "Le recueil des arrêts du TF", "Un journal cantonal"],
    correctIndex: 1,
    explanation: "La FF est la première déclaration de la loi ; on se base sur le RS (et le RO) pour les lois.",
    estimated: false,
  },
  {
    id: "q-bases-34", themeId,
    question: "Depuis le 1er janvier 2026, quelle version du RO et de la FF fait foi ?",
    choices: ["La version imprimée", "La version électronique", "Les deux de manière égale", "Celle du canton concerné"],
    correctIndex: 1,
    explanation: "Changement de primauté : c'est désormais la version électronique qui fait foi.",
    estimated: false,
  },
  {
    id: "q-bases-35", themeId,
    question: "Parmi les éléments suivants, lequel est dans la structure d'un arrêt ?",
    choices: ["Intitulé, préambule, corps, dispositions finales", "Préambule, état de fait, droit, dispositif", "Titre, chapitre, article, alinéa", "Faits, doctrine, coutume, loi"],
    correctIndex: 1,
    explanation: "Un arrêt comprend : préambule, état de fait, droit et dispositif (= la décision). L'autre structure est celle d'une loi fédérale.",
    estimated: false,
  },
  {
    id: "q-bases-36", themeId,
    question: "Quelle est la structure d'une loi fédérale ?",
    choices: ["Préambule, état de fait, droit, dispositif", "Intitulé, préambule, corps du texte, dispositions finales", "Faits, droit, dispositif", "Titre, source, jurisprudence"],
    correctIndex: 1,
    explanation: "Intitulé, préambule, corps du texte, dispositions finales.",
    estimated: false,
  },
  {
    id: "q-bases-37", themeId,
    question: "Où siège le Tribunal pénal fédéral ?",
    choices: ["Lausanne", "Bellinzone", "St-Gall", "Berne"],
    correctIndex: 1,
    explanation: "Le TPF siège à Bellinzone ; le Tribunal administratif fédéral et le Tribunal fédéral des brevets siègent à St-Gall.",
    estimated: false,
  },
  {
    id: "q-bases-38", themeId,
    question: "Quel tribunal statue sur les recours contre les décisions de l'administration fédérale ?",
    choices: ["Tribunal pénal fédéral", "Tribunal administratif fédéral (St-Gall)", "Tribunal fédéral des brevets", "Tribunal de police"],
    correctIndex: 1,
    explanation: "Le TAF statue sur les recours contre les décisions des services de l'administration fédérale et de certains gouvernements cantonaux.",
    estimated: false,
  },
  {
    id: "q-bases-39", themeId,
    question: "Quelle est la compétence du Tribunal fédéral des brevets ?",
    choices: ["Les litiges civils en matière de brevets et de contrefaçon, en 1ère instance", "Les infractions contre la Confédération", "Les recours contre l'administration", "Les litiges de bail"],
    correctIndex: 0,
    explanation: "Le Tribunal fédéral des brevets (St-Gall) juge en 1ère instance les litiges civils de brevets et de contrefaçon.",
    estimated: false,
  },
  {
    id: "q-bases-40", themeId,
    question: "Qu'est-ce que le syllogisme judiciaire ?",
    choices: ["Appliquer une règle générale et abstraite à une situation concrète pour en déduire une décision", "Créer une nouvelle loi", "Choisir la coutume la plus ancienne", "Mener une négociation entre parties"],
    correctIndex: 0,
    explanation: "Le juge applique la règle de droit aux faits qui en remplissent les conditions et en déduit la décision (faits – droit – dispositif).",
    estimated: false,
  },
  {
    id: "q-bases-41", themeId,
    question: "L'organisation des tribunaux relève de la compétence :",
    choices: ["Exclusive de la Confédération", "Des cantons (art. 122 et 123 Cst.), avec une organisation judiciaire fédérale", "Des communes", "De l'Union européenne"],
    correctIndex: 1,
    explanation: "Selon la Cst. (art. 122-123), l'organisation des tribunaux est cantonale, mais il existe une organisation judiciaire fédérale et la CEDH au niveau international.",
    estimated: false,
  },
  {
    id: "q-bases-42", themeId,
    question: "Une fois un jugement entré en force :",
    choices: ["Il peut toujours être renversé", "Il ne peut plus être annulé, sauf circonstances exceptionnelles", "Il doit être confirmé par le Parlement", "Il n'a plus d'effet"],
    correctIndex: 1,
    explanation: "Les tribunaux tranchent de manière définitive ; le jugement entré en force doit être considéré comme vrai.",
    estimated: false,
  },
  {
    id: "q-bases-43", themeId,
    question: "Quelles sont les garanties de procédure de l'art. 29 Cst. ?",
    choices: ["Procès équitable, interdiction du déni de justice formel, droit d'être entendu, assistance judiciaire gratuite", "Liberté d'opinion et de presse", "Droit de vote et d'éligibilité", "Garantie de la propriété"],
    correctIndex: 0,
    explanation: "Art. 29 Cst. : procès équitable et interdiction du déni de justice formel (al. 1), droit d'être entendu (al. 2), assistance judiciaire gratuite (al. 3). Fondement : art. 6 CEDH, art. 29, 30, 32 Cst.",
    estimated: false,
  },
  {
    id: "q-bases-44", themeId,
    question: "Qu'est-ce que l'élection de for ?",
    choices: ["Une exception aux règles légales de compétence territoriale", "Le choix du juge par le peuple", "Un recours au TF", "Une règle de compétence matérielle"],
    correctIndex: 0,
    explanation: "Compétence territoriale (lieu du procès) : le principe est que la loi fixe les règles ; l'exception est l'élection de for.",
    estimated: false,
  },
  {
    id: "q-bases-45", themeId,
    question: "Dans le droit subjectif, les « pouvoirs » sont :",
    choices: ["Des droits exercés dans l'intérêt propre du titulaire", "Des droits exercés dans l'intérêt d'autrui (ex. autorité parentale)", "Des droits envers la puissance publique", "Des obligations à exécuter"],
    correctIndex: 1,
    explanation: "Droits = intérêt propre ; pouvoirs = intérêt d'autrui ; libertés = vis-à-vis de la puissance publique ; obligations = ce que l'on doit exécuter.",
    estimated: false,
  },
  {
    id: "q-bases-46", themeId,
    question: "La « loi » au sens formel désigne :",
    choices: ["Toute règle de droit d'une autorité", "Uniquement les règles adoptées par le Parlement selon la procédure législative", "Une décision de justice", "Un usage local"],
    correctIndex: 1,
    explanation: "Au sens strict (formel), seules les règles adoptées par le Parlement (ex. LTVA, LAVS) ; au sens large (matériel), toute règle d'une autorité législative ou réglementaire (ex. ordonnances).",
    estimated: false,
  },
  {
    id: "q-bases-47", themeId,
    question: "Le droit intercantonal (concordat) est :",
    choices: ["Un accord entre deux ou plusieurs cantons, ex. Harmos", "Un traité international", "Une loi fédérale", "Une coutume"],
    correctIndex: 0,
    explanation: "Concordat ou convention entre cantons ; intégré dans les RO et RS de chaque canton concerné.",
    estimated: false,
  },
  {
    id: "q-bases-48", themeId,
    question: "Quelle est la principale différence entre droit public et droit privé ?",
    choices: ["Public : rapports verticaux avec l'État, intérêt général ; privé : rapports horizontaux entre particuliers", "Aucune", "Public : entre particuliers ; privé : avec l'État", "Le droit privé est toujours impératif"],
    correctIndex: 0,
    explanation: "Droit privé : rapports horizontaux, intérêts individuels. Droit public : rapports verticaux, intérêt général, règles souvent impératives.",
    estimated: false,
  },
  {
    id: "q-bases-49", themeId,
    question: "Comment appelle-t-on le droit objectif dans le langage courant du cours ?",
    choices: ["« Le droit »", "« Mes droits »", "« La jurisprudence »", "« Le droit de procédure »"],
    correctIndex: 0,
    explanation: "Droit objectif = « le droit » (les règles) ; droit subjectif = « mon/mes droit(s) ».",
    estimated: false,
  },
  {
    id: "q-bases-50", themeId,
    question: "Le droit subjectif est :",
    choices: ["L'ensemble des règles générales et abstraites", "L'ensemble des jugements des tribunaux", "Une règle non écrite", "Une prérogative accordée à une personne physique ou morale, dictée par le droit objectif"],
    correctIndex: 3,
    explanation: "Le droit subjectif est une prérogative accordée à une personne (de faire, d'exiger ou d'être obligée) ; il est dicté par le droit objectif (mise en œuvre).",
    estimated: false,
  },
  {
    id: "q-bases-51", themeId,
    question: "Combien de catégories compte le droit subjectif selon le cours ?",
    choices: ["2 : droits et devoirs", "3 : droits, libertés, garanties", "4 : droits, pouvoirs, libertés, obligations", "5 : droits, pouvoirs, libertés, obligations, sanctions"],
    correctIndex: 2,
    explanation: "Les 4 catégories : droits, pouvoirs, libertés, obligations.",
    estimated: false,
  },
  {
    id: "q-bases-52", themeId,
    question: "L'autorité parentale exercée dans l'intérêt de l'enfant est un exemple de :",
    choices: ["Droit", "Pouvoir", "Liberté", "Obligation"],
    correctIndex: 1,
    explanation: "Un pouvoir est un droit qu'une personne exerce dans l'intérêt d'autrui (ex. autorité parentale).",
    estimated: false,
  },
  {
    id: "q-bases-53", themeId,
    question: "L'égalité de traitement et la liberté de religion sont des exemples de :",
    choices: ["Libertés (droits vis-à-vis de la puissance publique)", "Pouvoirs", "Obligations", "Droits de procédure"],
    correctIndex: 0,
    explanation: "Les libertés sont les droits que les personnes ont vis-à-vis de la puissance publique, ex. droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-bases-54", themeId,
    question: "« Si je vends, je dois fournir la marchandise » est un exemple de :",
    choices: ["Pouvoir", "Liberté", "Droit objectif", "Obligation"],
    correctIndex: 3,
    explanation: "C'est l'exemple d'obligation donné en cours (obligation à exécuter).",
    estimated: false,
  },
  {
    id: "q-bases-55", themeId,
    question: "Une définition du droit donnée en cours est :",
    choices: ["L'ensemble des jugements rendus", "Un contrat entre particuliers", "Un ensemble de règles régissant les relations sociales", "L'ensemble des lois cantonales"],
    correctIndex: 2,
    explanation: "Le droit : ensemble de règles de conduite imposées à tous qui permettent la vie en société ; il encadre le comportement des personnes dans une société.",
    estimated: false,
  },
  {
    id: "q-bases-56", themeId,
    question: "Le respect du droit objectif est assuré par :",
    choices: ["La seule bonne volonté des personnes", "Des moyens de contrainte (sanction de la force publique)", "La coutume uniquement", "Des contrats entre particuliers"],
    correctIndex: 1,
    explanation: "Le droit objectif est assorti de moyens de contrainte (sanction de la force publique).",
    estimated: false,
  },
  {
    id: "q-bases-57", themeId,
    question: "Le droit de fond est aussi appelé :",
    choices: ["Droit matériel", "Droit formel", "Droit de procédure", "Droit dispositif"],
    correctIndex: 0,
    explanation: "Droit de fond = droit matériel (le contenu) ; droit de procédure = droit formel.",
    estimated: false,
  },
  {
    id: "q-bases-58", themeId,
    question: "Le droit de procédure est aussi appelé :",
    choices: ["Droit matériel", "Droit de fond", "Droit impératif", "Droit formel"],
    correctIndex: 3,
    explanation: "Droit de procédure = droit formel : il règle la mise en œuvre des droits subjectifs et organise les voies de recours.",
    estimated: false,
  },
  {
    id: "q-bases-59", themeId,
    question: "L'art. 361 CO est un exemple de :",
    choices: ["Droit dispositif", "Droit de procédure", "Droit impératif", "Droit international"],
    correctIndex: 2,
    explanation: "Art. 361 CO : exemple de droit impératif ; art. 364 al. 3 CO : exemple de droit dispositif.",
    estimated: false,
  },
  {
    id: "q-bases-60", themeId,
    question: "L'art. 364 al. 3 CO est un exemple de :",
    choices: ["Droit impératif", "Droit dispositif", "Droit pénal", "Droit constitutionnel"],
    correctIndex: 1,
    explanation: "Le droit dispositif peut être écarté par accord entre les parties.",
    estimated: false,
  },
  {
    id: "q-bases-61", themeId,
    question: "Le droit national est aussi appelé :",
    choices: ["Droit interne", "Droit externe", "Droit positif", "Droit dispositif"],
    correctIndex: 0,
    explanation: "Droit national = droit interne ; droit international = droit externe.",
    estimated: false,
  },
  {
    id: "q-bases-62", themeId,
    question: "Le droit international est aussi appelé :",
    choices: ["Droit interne", "Droit de fond", "Droit privé", "Droit externe"],
    correctIndex: 3,
    explanation: "Il s'applique à plusieurs États ou entre plusieurs États.",
    estimated: false,
  },
  {
    id: "q-bases-63", themeId,
    question: "Le droit national s'applique :",
    choices: ["À plusieurs États", "À toute l'Europe", "À une population donnée, sur un territoire donné, à un moment donné", "Uniquement aux étrangers"],
    correctIndex: 2,
    explanation: "Définition du droit national, qui se décline en trois niveaux (fédéral, cantonal, communal).",
    estimated: false,
  },
  {
    id: "q-bases-64", themeId,
    question: "La distinction droit public / droit privé existe-t-elle aussi en droit international ?",
    choices: ["Non, le droit international est toujours public", "Oui, il y a aussi un droit international public et privé", "Non, il est toujours privé", "Seulement en droit pénal"],
    correctIndex: 1,
    explanation: "Le cours précise que la distinction entre droit public et droit privé existe en droit national comme en droit international.",
    estimated: false,
  },
  {
    id: "q-bases-65", themeId,
    question: "Les rapports en droit privé sont dits :",
    choices: ["Horizontaux (parties sur un pied d'égalité)", "Verticaux", "Hiérarchiques", "Impératifs"],
    correctIndex: 0,
    explanation: "Droit privé : rapports horizontaux entre personnes physiques ou morales sur un pied d'égalité.",
    estimated: false,
  },
  {
    id: "q-bases-66", themeId,
    question: "Les rapports en droit public sont dits :",
    choices: ["Horizontaux", "Contractuels", "Dispositifs", "Verticaux (les parties ne sont pas sur un pied d'égalité)"],
    correctIndex: 3,
    explanation: "Rapports verticaux entre l'État et les particuliers ; vise à protéger l'intérêt général.",
    estimated: false,
  },
  {
    id: "q-bases-67", themeId,
    question: "Le droit privé vise à :",
    choices: ["Protéger l'intérêt général", "Organiser l'État", "Assurer la sauvegarde des intérêts individuels", "Sanctionner les infractions"],
    correctIndex: 2,
    explanation: "Le droit public protège l'intérêt général ; le droit privé les intérêts individuels.",
    estimated: false,
  },
  {
    id: "q-bases-68", themeId,
    question: "Le droit public :",
    choices: ["Régit uniquement les contrats", "Organise l'État et règle son fonctionnement et ses attributions", "Ne contient jamais de sanctions", "Ne s'applique qu'aux entreprises"],
    correctIndex: 1,
    explanation: "Il régit les relations État – particulier ; ses règles sont souvent impératives avec des sanctions strictes.",
    estimated: false,
  },
  {
    id: "q-bases-69", themeId,
    question: "Le droit des assurances sociales relève :",
    choices: ["Du droit public", "Du droit privé", "Du droit international uniquement", "Du droit commercial"],
    correctIndex: 0,
    explanation: "Classement de l'exercice du cours : l'assurance sociale (ex. assurance-maladie de base) est du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-70", themeId,
    question: "Le droit fiscal relève :",
    choices: ["Du droit privé", "Du droit des obligations", "Du droit des sociétés", "Du droit public"],
    correctIndex: 3,
    explanation: "L'État prélève l'impôt : rapport vertical.",
    estimated: false,
  },
  {
    id: "q-bases-71", themeId,
    question: "Le droit bancaire relève :",
    choices: ["Du droit public", "Du droit constitutionnel", "Du droit privé", "Du droit pénal"],
    correctIndex: 2,
    explanation: "Exercice de classement du cours : le droit bancaire est du droit privé.",
    estimated: false,
  },
  {
    id: "q-bases-72", themeId,
    question: "Le droit des sociétés relève :",
    choices: ["Du droit public", "Du droit privé", "Du droit administratif", "Du droit pénal des mineurs"],
    correctIndex: 1,
    explanation: "Droit privé, comme le droit des contrats et des obligations.",
    estimated: false,
  },
  {
    id: "q-bases-73", themeId,
    question: "Le droit des contrats relève :",
    choices: ["Du droit privé", "Du droit public", "Du droit administratif", "Du droit fiscal"],
    correctIndex: 0,
    explanation: "Il régit des rapports entre particuliers.",
    estimated: false,
  },
  {
    id: "q-bases-74", themeId,
    question: "La poursuite pour dettes et faillites relève :",
    choices: ["Du droit privé", "Du droit commercial", "De la coutume", "Du droit public"],
    correctIndex: 3,
    explanation: "Exercice de classement du cours : droit public.",
    estimated: false,
  },
  {
    id: "q-bases-75", themeId,
    question: "Le droit pénal des mineurs relève :",
    choices: ["Du droit privé", "Du droit des personnes", "Du droit public", "Du droit réel"],
    correctIndex: 2,
    explanation: "Comme le droit pénal, il oppose l'État à la personne poursuivie.",
    estimated: false,
  },
  {
    id: "q-bases-76", themeId,
    question: "Pascal doit payer chaque mois sa prime d'assurance-maladie de base. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Droit international"],
    correctIndex: 1,
    explanation: "Wooclap : l'assurance-maladie de base (assurance sociale) relève du droit public, tandis que l'assurance complémentaire (Georges) est du droit privé.",
    estimated: false,
  },
  {
    id: "q-bases-77", themeId,
    question: "Quelles sont les 4 grandes divisions du droit public (schéma du cours) ?",
    choices: ["Droit administratif, constitutionnel, pénal et de procédure", "Droit civil, obligations, commercial, PI", "Droit des personnes, famille, réel, successions", "Droit du travail, bancaire, fiscal, des sociétés"],
    correctIndex: 0,
    explanation: "Public : administratif, constitutionnel, pénal, procédure (CPC, CPP, PA).",
    estimated: false,
  },
  {
    id: "q-bases-78", themeId,
    question: "Quelles sont les 4 grandes divisions du droit privé (schéma du cours) ?",
    choices: ["Droit administratif, constitutionnel, pénal, procédure", "Droit civil, pénal, administratif, fiscal", "Droit des obligations, pénal, commercial, PI", "Droit civil, des obligations, commercial et de la propriété intellectuelle"],
    correctIndex: 3,
    explanation: "Le droit civil se subdivise en droit des personnes, de la famille, réel et des successions.",
    estimated: false,
  },
  {
    id: "q-bases-79", themeId,
    question: "Le droit civil se subdivise en :",
    choices: ["CPC, CPP, PA", "Droit administratif, pénal, constitutionnel", "Droit des personnes, de la famille, réel et des successions", "Droit commercial et PI"],
    correctIndex: 2,
    explanation: "Schéma des domaines du droit.",
    estimated: false,
  },
  {
    id: "q-bases-80", themeId,
    question: "CPC, CPP et PA sont :",
    choices: ["Des lois de droit des obligations", "Des règles de droit de procédure (droit public)", "Des sources de la coutume", "Des tribunaux"],
    correctIndex: 1,
    explanation: "Sous « droit de procédure » du droit public : CPC (civile), CPP (pénale), PA (procédure administrative).",
    estimated: false,
  },
  {
    id: "q-bases-81", themeId,
    question: "Le droit se manifeste de deux manières :",
    choices: ["Par des normes (générales et abstraites) et par des décisions ou jugements (cas particulier)", "Par la loi et la Constitution", "Par le droit privé et public", "Par le contrat et la coutume"],
    correctIndex: 0,
    explanation: "Normes = de manière générale ; décisions/jugements = de manière concrète.",
    estimated: false,
  },
  {
    id: "q-bases-82", themeId,
    question: "Une décision ou un jugement :",
    choices: ["Est général et abstrait", "S'applique à tous", "Est une loi", "Concerne un cas particulier, de manière concrète"],
    correctIndex: 3,
    explanation: "Contrairement aux normes (droit objectif), les décisions règlent un cas particulier.",
    estimated: false,
  },
  {
    id: "q-bases-83", themeId,
    question: "La pyramide des normes du cours, de haut en bas :",
    choices: ["Constitution, DI, loi, ordonnances, autres actes", "Loi, Constitution, DI, ordonnances, autres actes", "DI, Constitution, loi, ordonnances, autres actes", "DI, loi, Constitution, autres actes, ordonnances"],
    correctIndex: 2,
    explanation: "En Suisse, le droit international est supérieur au droit national ; chaque norme doit être conforme à une norme supérieure.",
    estimated: false,
  },
  {
    id: "q-bases-84", themeId,
    question: "En cas de conflit, chaque norme juridique doit :",
    choices: ["Être conforme à une norme inférieure", "Être conforme à une norme supérieure", "Être conforme à la coutume locale", "Être approuvée par le TF"],
    correctIndex: 1,
    explanation: "Principe de hiérarchie des normes.",
    estimated: false,
  },
  {
    id: "q-bases-85", themeId,
    question: "Quelle est la législation fédérale selon le cours ?",
    choices: ["Cst. fédérale, loi fédérale, code, arrêté fédéral, ordonnance législative", "Cst. cantonale, loi cantonale, loi intercantonale", "Règlement communal et intercommunal", "Concordats uniquement"],
    correctIndex: 0,
    explanation: "Cantonale : Cst. cantonale, loi cantonale, loi intercantonale. Communale : règlement communal, règlement intercommunal.",
    estimated: false,
  },
  {
    id: "q-bases-86", themeId,
    question: "Quelle est la législation communale selon le cours ?",
    choices: ["Loi communale et ordonnance", "Cst. communale", "Arrêté fédéral", "Règlement communal et règlement intercommunal"],
    correctIndex: 3,
    explanation: "La législation communale : règlement communal et intercommunal.",
    estimated: false,
  },
  {
    id: "q-bases-87", themeId,
    question: "Harmos est un exemple de :",
    choices: ["Droit international", "Loi fédérale", "Droit intercantonal (concordat)", "Coutume"],
    correctIndex: 2,
    explanation: "Concordat ou convention entre deux ou plusieurs cantons.",
    estimated: false,
  },
  {
    id: "q-bases-88", themeId,
    question: "Où le droit intercantonal est-il intégré ?",
    choices: ["Uniquement au RS fédéral", "Dans les RO et RS de chaque canton concerné", "Dans la FF", "Dans les revues de doctrine"],
    correctIndex: 1,
    explanation: "Il est intégré dans les RO et RS de chaque canton concerné.",
    estimated: false,
  },
  {
    id: "q-bases-89", themeId,
    question: "Que contient le RO ?",
    choices: ["Tous les textes normatifs : Constitution, lois, arrêtés, ordonnances, traités internationaux, traités Confédération-cantons", "Uniquement les arrêts du TF", "Uniquement les ordonnances", "Les opinions de doctrine"],
    correctIndex: 0,
    explanation: "Le RO est classé chronologiquement.",
    estimated: false,
  },
  {
    id: "q-bases-90", themeId,
    question: "En combien de thématiques la matière du RS est-elle répartie ?",
    choices: ["Trois", "Cinq", "Douze", "Neuf"],
    correctIndex: 3,
    explanation: "Le RS est classé par domaine/matière en neuf thématiques.",
    estimated: false,
  },
  {
    id: "q-bases-91", themeId,
    question: "Chaque canton dispose-t-il de son RO et de son RS ?",
    choices: ["Non, seule la Confédération en a", "Seulement un RS", "Oui (ex. RSJU, RSN)", "Seulement un RO"],
    correctIndex: 2,
    explanation: "Les cantons disposent chacun d'un RO et d'un RS.",
    estimated: false,
  },
  {
    id: "q-bases-92", themeId,
    question: "Que doit-on vérifier en cherchant une loi via Google ?",
    choices: ["Que le site est en français", "Que l'on a la bonne version", "Que la loi est cantonale", "Rien du tout"],
    correctIndex: 1,
    explanation: "Le cours avertit : s'assurer d'avoir la bonne version.",
    estimated: false,
  },
  {
    id: "q-bases-93", themeId,
    question: "La coutume est :",
    choices: ["Généralement du droit non écrit", "Du droit écrit adopté par le Parlement", "Une décision du TF", "Un contrat"],
    correctIndex: 0,
    explanation: "Ensemble de règles non écrites résultant d'un usage implanté, tenu pour juridiquement obligatoire.",
    estimated: false,
  },
  {
    id: "q-bases-94", themeId,
    question: "Une règle devient coutume si elle est reconnue par la collectivité comme :",
    choices: ["Simplement pratique", "Facultative", "Écrite dans la FF", "Juridiquement contraignante"],
    correctIndex: 3,
    explanation: "Conditions : droit non écrit, usage durable, reconnu comme juridiquement contraignant.",
    estimated: false,
  },
  {
    id: "q-bases-95", themeId,
    question: "« ATF 119 IV 59 » désigne :",
    choices: ["Une loi fédérale", "Un article du CC", "Un arrêt du Tribunal fédéral", "Une ordonnance"],
    correctIndex: 2,
    explanation: "ATF = Arrêt du Tribunal fédéral ; consultables sur www.bger.ch.",
    estimated: false,
  },
  {
    id: "q-bases-96", themeId,
    question: "Où trouve-t-on les arrêts du TF ?",
    choices: ["Uniquement dans le RS", "Au Recueil officiel des arrêts du TF et sur www.bger.ch", "Sur fedlex uniquement", "Dans la FF"],
    correctIndex: 1,
    explanation: "Au niveau fédéral : Recueil officiel des arrêts du TF, www.bger.ch.",
    estimated: false,
  },
  {
    id: "q-bases-97", themeId,
    question: "Pourquoi la jurisprudence cantonale est-elle souvent plus difficile à trouver ?",
    choices: ["Chaque canton publie ses décisions selon ses propres pratiques", "Elle est secrète", "Elle n'existe pas", "Le TF la publie seul"],
    correctIndex: 0,
    explanation: "Chaque canton est responsable de la publication de ses décisions.",
    estimated: false,
  },
  {
    id: "q-bases-98", themeId,
    question: "Qui est responsable de veiller à l'application uniforme du droit fédéral ?",
    choices: ["Le Conseil fédéral", "Le Parlement", "Les cantons", "Le Tribunal fédéral"],
    correctIndex: 3,
    explanation: "Il appartient au TF de veiller à une application uniforme du droit fédéral.",
    estimated: false,
  },
  {
    id: "q-bases-99", themeId,
    question: "La doctrine est utilisée par les tribunaux pour :",
    choices: ["Créer la Constitution", "Élire les juges", "Appliquer le droit et le faire évoluer", "Publier la FF"],
    correctIndex: 2,
    explanation: "Outil essentiel utilisé par les tribunaux.",
    estimated: false,
  },
  {
    id: "q-bases-100", themeId,
    question: "Quels sont des exemples de lieux où trouver la doctrine ?",
    choices: ["RO et RS", "Bibliothèques, revues, thèses, sites spécialisés (Schulthess, Legalis), librairies", "bger.ch", "FF"],
    correctIndex: 1,
    explanation: "Ouvrages, revues, thèses, bases de données en ligne.",
    estimated: false,
  },
  {
    id: "q-bases-101", themeId,
    question: "Qui écrit la doctrine ?",
    choices: ["Juristes, professeurs d'université, juges (milieu académique)", "Le Parlement", "Le Conseil fédéral", "Les tribunaux uniquement"],
    correctIndex: 0,
    explanation: "Notes du cours : juristes, profs d'uni, juges, domaine académique ou universitaire.",
    estimated: false,
  },
  {
    id: "q-bases-102", themeId,
    question: "Toute règle de droit est en principe assortie :",
    choices: ["D'un contrat", "D'une coutume", "D'un recours automatique", "D'une sanction"],
    correctIndex: 3,
    explanation: "Principe de l'organisation de la justice.",
    estimated: false,
  },
  {
    id: "q-bases-103", themeId,
    question: "La justice a pour but de trancher les litiges de droit :",
    choices: ["Constitutionnel uniquement", "International uniquement", "Pénal, administratif et privé", "Fiscal uniquement"],
    correctIndex: 2,
    explanation: "Elle tranche les litiges pénaux, administratifs et privés.",
    estimated: false,
  },
  {
    id: "q-bases-104", themeId,
    question: "Les 3 échelons de l'organisation judiciaire sont :",
    choices: ["Communal, cantonal, fédéral", "Cantonal, fédéral, international", "Régional, national, européen", "Civil, pénal, administratif"],
    correctIndex: 1,
    explanation: "Cantonal – fédéral – international (CEDH).",
    estimated: false,
  },
  {
    id: "q-bases-105", themeId,
    question: "Que fait la CEDH dans l'organisation de la justice du cours ?",
    choices: ["Elle constitue le pouvoir judiciaire « international » (Cour européenne des droits de l'Homme)", "Elle légifère", "Elle remplace le TF pour les litiges civils", "Elle juge en première instance les délits routiers"],
    correctIndex: 0,
    explanation: "Wooclap : après épuisement des instances suisses, pour violation des droits fondamentaux, on peut saisir la CEDH.",
    estimated: false,
  },
  {
    id: "q-bases-106", themeId,
    question: "Quel tribunal fédéral siège à St-Gall ?",
    choices: ["Le Tribunal pénal fédéral", "Le Tribunal fédéral seul", "Aucun", "Le Tribunal administratif fédéral et le Tribunal fédéral des brevets"],
    correctIndex: 3,
    explanation: "TPF = Bellinzone ; TAF et brevets = St-Gall.",
    estimated: false,
  },
  {
    id: "q-bases-107", themeId,
    question: "Les tribunaux spéciaux fédéraux sont :",
    choices: ["TF, TC, CEDH", "Tribunal de police, tribunal régional, tribunal cantonal", "TPF, TAF, Tribunal fédéral des brevets", "Tribunal des baux, prud'hommes, TC"],
    correctIndex: 2,
    explanation: "Le TF est l'instance suprême ; les tribunaux spéciaux : TPF, TAF, Tribunal des brevets.",
    estimated: false,
  },
  {
    id: "q-bases-108", themeId,
    question: "Que peut juger le TPF en première instance ?",
    choices: ["Les litiges de voisinage", "Infractions visant les intérêts de la Confédération, crime organisé, etc.", "Les recours contre l'administration", "Les litiges de brevets"],
    correctIndex: 1,
    explanation: "Notamment pour les infractions visant les intérêts de la Confédération, la criminalité organisée.",
    estimated: false,
  },
  {
    id: "q-bases-109", themeId,
    question: "Quel est le schéma des voies de recours ?",
    choices: ["1re instance cantonale → 2e instance cantonale → TF (et TAF/TPF → TF)", "TF → cantons → communes", "Commune → canton → CEDH directement", "Aucun recours n'existe"],
    correctIndex: 0,
    explanation: "Pyramide du cours : autorités cantonales de 1re instance, 2e instance, TAF/TPF, puis TF, via recours.",
    estimated: false,
  },
  {
    id: "q-bases-110", themeId,
    question: "En matière civile, quelle est la chaîne de recours (schéma) ?",
    choices: ["Tribunal pénal fédéral → TF", "Tribunal de police → TPF", "Tribunal des baux → CEDH", "Tribunal civil → Tribunal cantonal/Cour suprême → Tribunal fédéral"],
    correctIndex: 3,
    explanation: "Schéma de la juridiction civile (CC, CO), avec le Tribunal fédéral des brevets en parallèle pour les brevets.",
    estimated: false,
  },
  {
    id: "q-bases-111", themeId,
    question: "En matière administrative, qui est la dernière instance fédérale ?",
    choices: ["Le Conseil fédéral", "La CEDH uniquement", "Le Tribunal fédéral (après le TAF ou le tribunal administratif cantonal)", "Le tribunal de police"],
    correctIndex: 2,
    explanation: "Juridiction administrative : instance de recours interne → tribunal administratif (cantonal ou TAF) → TF.",
    estimated: false,
  },
  {
    id: "q-bases-112", themeId,
    question: "Les tribunaux de première instance (régionaux) du canton de Neuchâtel sont :",
    choices: ["Le Tribunal cantonal et le TF", "Montagnes et Val-de-Ruz (10 juges) et Littoral et Val-de-Travers (15 juges)", "La Cour civile et la Cour pénale", "Le Tribunal des Prud'hommes et le Tribunal arbitral"],
    correctIndex: 1,
    explanation: "Tribunal régional des Montagnes et du Val-de-Ruz (CDF) et du Littoral et du Val-de-Travers (CNE, Boudry).",
    estimated: false,
  },
  {
    id: "q-bases-113", themeId,
    question: "Quelle section est composée dans un tribunal régional neuchâtelois ?",
    choices: ["Chambre de conciliation, tribunal civil, APEA, tribunal pénal des mineurs, tribunal de police, tribunal criminel, tribunal des mesures de contrainte", "Cour civile et Cour pénale", "Tribunal arbitral", "Cour de droit public"],
    correctIndex: 0,
    explanation: "Composition des sections des tribunaux régionaux.",
    estimated: false,
  },
  {
    id: "q-bases-114", themeId,
    question: "Quelle Cour fait partie du Tribunal cantonal neuchâtelois ?",
    choices: ["Tribunal de police", "Tribunal criminel", "Chambre de conciliation", "Cour civile, Cour pénale, Cour de droit public, Cour des mesures de protection de l'enfant et de l'adulte, autorité de recours en matière pénale, Tribunal arbitral"],
    correctIndex: 3,
    explanation: "Le Tribunal cantonal est l'autorité judiciaire cantonale de recours (2e instance).",
    estimated: false,
  },
  {
    id: "q-bases-115", themeId,
    question: "Les règles de procédure sont :",
    choices: ["Les règles de fond sur les contrats", "Des coutumes locales", "Les formalités prévues par la loi pour agir en justice (qualité pour agir, délais, compétence, forme, représentation, récusation)", "Des règles de doctrine"],
    correctIndex: 2,
    explanation: "Définition du cours.",
    estimated: false,
  },
  {
    id: "q-bases-116", themeId,
    question: "La compétence matérielle des tribunaux :",
    choices: ["Se rapporte au lieu du procès", "Se rapporte au sujet du procès", "Désigne le juge choisi par les parties", "N'existe pas en Suisse"],
    correctIndex: 1,
    explanation: "Territoriale = lieu ; matérielle = sujet.",
    estimated: false,
  },
  {
    id: "q-bases-117", themeId,
    question: "La compétence territoriale :",
    choices: ["Se rapporte au lieu du procès ; en principe fixée par la loi, exception : élection de for", "Se rapporte au sujet du procès", "Est toujours choisie librement", "Est du ressort du TF"],
    correctIndex: 0,
    explanation: "Principe : règles légales ; exception : élection de for.",
    estimated: false,
  },
  {
    id: "q-bases-118", themeId,
    question: "Les tribunaux civils jugent :",
    choices: ["Les litiges de droit public", "Les infractions", "Les recours fédéraux", "Les litiges entre particuliers"],
    correctIndex: 3,
    explanation: "Civils : particuliers ; administratifs : droit public ; pénaux : matière pénale.",
    estimated: false,
  },
  {
    id: "q-bases-119", themeId,
    question: "Les tribunaux administratifs jugent :",
    choices: ["Les litiges entre particuliers", "Les infractions pénales", "Les litiges de droit public (administratif)", "Les litiges de brevets"],
    correctIndex: 2,
    explanation: "Compétence matérielle.",
    estimated: false,
  },
  {
    id: "q-bases-120", themeId,
    question: "Quels articles fondent les garanties de procédure ?",
    choices: ["Art. 1 CC", "Art. 6 CEDH et art. 29, 30, 32 Cst.", "Art. 5 et 190 Cst.", "Art. 361 et 364 CO"],
    correctIndex: 1,
    explanation: "Fondements des garanties fondamentales de procédure.",
    estimated: false,
  },
  {
    id: "q-bases-121", themeId,
    question: "Le droit à un procès équitable est ancré à :",
    choices: ["Art. 29 al. 1 Cst.", "Art. 29 al. 2 Cst.", "Art. 29 al. 3 Cst.", "Art. 10 Cst."],
    correctIndex: 0,
    explanation: "Art. 29 al. 1 : procès équitable et interdiction du déni de justice formel.",
    estimated: false,
  },
  {
    id: "q-bases-122", themeId,
    question: "Le droit d'être entendu est ancré à :",
    choices: ["Art. 29 al. 1 Cst.", "Art. 29 al. 3 Cst.", "Art. 36 Cst.", "Art. 29 al. 2 Cst."],
    correctIndex: 3,
    explanation: "Art. 29 al. 2 Cst.",
    estimated: false,
  },
  {
    id: "q-bases-123", themeId,
    question: "L'assistance judiciaire gratuite et celle d'un défenseur sont ancrées à :",
    choices: ["Art. 29 al. 1 Cst.", "Art. 29 al. 2 Cst.", "Art. 29 al. 3 Cst.", "Art. 30 Cst."],
    correctIndex: 2,
    explanation: "Art. 29 al. 3 Cst.",
    estimated: false,
  },
  {
    id: "q-bases-124", themeId,
    question: "L'interdiction du déni de justice formel est ancrée à :",
    choices: ["Art. 29 al. 2 Cst.", "Art. 29 al. 1 Cst.", "Art. 29 al. 3 Cst.", "Art. 190 Cst."],
    correctIndex: 1,
    explanation: "Avec le procès équitable.",
    estimated: false,
  },
  {
    id: "q-bases-125", themeId,
    question: "Que dit l'art. 1 al. 1 CC ?",
    choices: ["La loi régit toutes les matières auxquelles se rapportent la lettre ou l'esprit de l'une de ses dispositions", "Le juge prononce selon le droit coutumier", "Le juge s'inspire de la doctrine", "Les cantons sont souverains"],
    correctIndex: 0,
    explanation: "Principe de la primauté de la loi.",
    estimated: false,
  },
  {
    id: "q-bases-126", themeId,
    question: "Que dit l'art. 1 al. 2 CC ?",
    choices: ["La loi régit toutes les matières", "Le juge s'inspire de la jurisprudence", "Le TF crée les lois", "À défaut de disposition légale applicable, le juge prononce selon le droit coutumier et, à défaut de coutume, selon les règles qu'il établirait s'il avait à faire acte de législateur"],
    correctIndex: 3,
    explanation: "Ordre : loi, puis coutume, puis règle que le juge établirait comme législateur.",
    estimated: false,
  },
  {
    id: "q-bases-127", themeId,
    question: "Que dit l'art. 1 al. 3 CC ?",
    choices: ["La loi prime toujours", "À défaut de loi, la coutume s'applique", "Le juge s'inspire des solutions consacrées par la doctrine et la jurisprudence", "Les tribunaux sont cantonaux"],
    correctIndex: 2,
    explanation: "Doctrine et jurisprudence : solutions dont le juge s'inspire.",
    estimated: false,
  },
  {
    id: "q-bases-128", themeId,
    question: "« Justes motifs » est un exemple de :",
    choices: ["Notion évolutive", "Notion non définie par la loi", "Contradiction légale", "Formulation complète"],
    correctIndex: 1,
    explanation: "Difficulté d'application : notions pas définies (ex. justes motifs).",
    estimated: false,
  },
  {
    id: "q-bases-129", themeId,
    question: "« Bonne foi » ou « usage » sont des exemples de :",
    choices: ["Notions évolutives", "Notions non définies uniquement", "Règles impératives", "Sources du droit"],
    correctIndex: 0,
    explanation: "Difficulté d'application : notions évolutives.",
    estimated: false,
  },
  {
    id: "q-bases-130", themeId,
    question: "Pourquoi l'application du droit pose-t-elle des difficultés ?",
    choices: ["Les lois sont toujours très précises", "Les juges ne lisent pas la loi", "Le droit est uniquement oral", "Le texte de la loi est général alors que les situations sont particulières"],
    correctIndex: 3,
    explanation: "Notions non définies, évolutives, formulation incomplète, lacune ou contradiction.",
    estimated: false,
  },
  {
    id: "q-bases-131", themeId,
    question: "Pourquoi le juge interprète-t-il la loi ?",
    choices: ["Pour créer de nouvelles lois", "Pour contourner le Parlement", "Pour garantir l'égalité devant la loi", "Pour éviter les recours"],
    correctIndex: 2,
    explanation: "Le juge veille à ce que la loi soit appliquée de manière égale à tous.",
    estimated: false,
  },
  {
    id: "q-bases-132", themeId,
    question: "Qui peut interpréter le droit ?",
    choices: ["Uniquement le TF", "Juges, autorités, avocats, particuliers", "Uniquement le Parlement", "Uniquement les juristes de l'État"],
    correctIndex: 1,
    explanation: "L'interprétation est pratiquée par différentes personnes.",
    estimated: false,
  },
  {
    id: "q-bases-133", themeId,
    question: "Dans le syllogisme judiciaire, le juge applique :",
    choices: ["Une règle de droit (générale et abstraite) à une situation concrète (les faits) pour en déduire la décision", "Le jugement entré en force", "La décision d'un autre tribunal", "La coutume"],
    correctIndex: 0,
    explanation: "Règle de droit + faits concrets → décision (dispositif).",
    estimated: false,
  },
  {
    id: "q-bases-134", themeId,
    question: "La structure d'une décision est :",
    choices: ["Droit – coutume – doctrine", "Préambule – corps – dispositions finales", "Intitulé – titre – article", "Faits – droit – dispositif"],
    correctIndex: 3,
    explanation: "Pour les arrêts : préambule, état de fait, droit, dispositif.",
    estimated: false,
  },
  {
    id: "q-bases-135", themeId,
    question: "Le dispositif d'un arrêt est :",
    choices: ["L'état de fait", "Le préambule", "La décision", "La doctrine citée"],
    correctIndex: 2,
    explanation: "Dispositif (= décision).",
    estimated: false,
  },
  {
    id: "q-bases-136", themeId,
    question: "Une personne privée peut-elle rendre une décision (au sens du cours) ?",
    choices: ["Oui, toujours", "Non (Wooclap : seules les autorités)", "Oui, par contrat", "Oui, pour les litiges de voisinage"],
    correctIndex: 1,
    explanation: "Wooclap : 79 % ont répondu Non ; les décisions émanent d'autorités.",
    estimated: false,
  },
  {
    id: "q-bases-137", themeId,
    question: "Maxime est arrêté pour conduite en état d'ébriété : quel droit ?",
    choices: ["Droit public (pénal)", "Droit privé", "Droit des contrats", "Droit des successions"],
    correctIndex: 0,
    explanation: "Wooclap : l'État sanctionne, rapport vertical.",
    estimated: false,
  },
  {
    id: "q-bases-138", themeId,
    question: "La liberté de la presse est garantie : quel droit ?",
    choices: ["Droit privé", "Droit des obligations", "Droit commercial", "Droit public (droits fondamentaux)"],
    correctIndex: 3,
    explanation: "Wooclap : 89 % droit public.",
    estimated: false,
  },
  {
    id: "q-bases-139", themeId,
    question: "Un traité international entre pays relève du :",
    choices: ["Droit privé", "Droit des contrats", "Droit public", "Droit civil"],
    correctIndex: 2,
    explanation: "Wooclap : relations entre États.",
    estimated: false,
  },
  {
    id: "q-bases-140", themeId,
    question: "Qui édicte les lois fédérales ?",
    choices: ["Le Conseil fédéral seul", "Le Conseil national et le Conseil des États (Assemblée fédérale)", "Les tribunaux", "Le Conseil national et le Conseil d'État"],
    correctIndex: 1,
    explanation: "Wooclap : la loi émane du peuple et de l'Assemblée fédérale.",
    estimated: false,
  },
];
