import { QuizQuestion } from "@/models/types";

// Contenu réel (estimated: false) — Chapitre 1 "Les bases du droit"
// (support de cours PGD IG 25/26) et Wooclap "IG - Les bases du droit - 2025".
// Pour ajouter une question : copie un bloc, change l'id, et garde
// correctIndex cohérent avec l'ordre de `choices` (le mélange est fait
// automatiquement à l'affichage, pas besoin d'y penser ici).

const themeId = "bases-du-droit";

export const quizBasesDuDroit: QuizQuestion[] = [
  {
    id: "q-bases-01", themeId,
    question: "Quelle est la meilleure définition du droit objectif ?",
    choices: ["L'ensemble des droits d'une personne", "L'ensemble des règles générales et abstraites imposées par une autorité compétente", "L'ensemble des décisions de justice", "Un ensemble de règles non écrites reconnues par la société"],
    correctIndex: 1,
    explanation: "Le droit objectif est l'ensemble de règles générales et abstraites qui indiquent ce qui doit être fait, édictées ou reconnues par une autorité compétente, et dont le respect est assuré par des moyens de contrainte.",
    estimated: false,
  },
  {
    id: "q-bases-02", themeId,
    question: "La règle de droit est dite « abstraite » car :",
    choices: ["Elle s'applique à une personne spécifique", "Elle est imposée uniquement par l'État", "Elle s'applique à un nombre indéterminé de situations concrètes", "Elle n'a pas de contrainte légale"],
    correctIndex: 2,
    explanation: "Une règle générale et abstraite vise un nombre indéterminé de cas et de personnes, contrairement à une décision individuelle qui vise un cas particulier.",
    estimated: false,
  },
  {
    id: "q-bases-03", themeId,
    question: "Le droit impératif se distingue du droit dispositif car :",
    choices: ["Il peut être modifié par les parties en accord", "Il s'applique uniquement en cas de litige", "Il doit être respecté par tout le monde, sans possibilité de dérogation", "Il est appliqué uniquement dans le domaine du droit pénal"],
    correctIndex: 2,
    explanation: "Le droit impératif (ex. art. 361 CO) ne peut pas être écarté par accord entre les parties, contrairement au droit dispositif (ex. art. 364 al. 3 CO) qui ne s'applique qu'à défaut d'accord contraire.",
    estimated: false,
  },
  {
    id: "q-bases-04", themeId,
    question: "Parmi les sources du droit suivantes, lesquelles sont des sources secondaires ?",
    choices: ["La loi et le règlement", "La jurisprudence et la doctrine", "Uniquement la coutume", "La Constitution fédérale"],
    correctIndex: 1,
    explanation: "La loi est la source primaire du droit suisse. La coutume, la jurisprudence et la doctrine sont des sources secondaires, utilisées notamment en cas de lacune de la loi.",
    estimated: false,
  },
  {
    id: "q-bases-05", themeId,
    question: "Le droit du travail relève-t-il principalement du droit public ou du droit privé ?",
    choices: ["Droit public", "Droit privé", "Les deux, selon le contexte", "Ni l'un ni l'autre"],
    correctIndex: 2,
    explanation: "Le droit du travail relève principalement du droit privé (relation employeur-employé), mais comporte aussi des aspects de droit public (protection des travailleurs, droit public du travail).",
    estimated: false,
  },
  {
    id: "q-bases-06", themeId,
    question: "Selon la hiérarchie des normes en Suisse, quelle norme interne est supérieure aux autres ?",
    choices: ["La loi cantonale", "La Constitution fédérale", "Le règlement communal", "L'ordonnance législative"],
    correctIndex: 1,
    explanation: "Dans la hiérarchie des normes, seul le droit international prime sur la Constitution fédérale, qui est elle-même supérieure aux lois, ordonnances et autres actes internes.",
    estimated: false,
  },
  {
    id: "q-bases-07", themeId,
    question: "Le droit formel (droit de procédure) :",
    choices: ["Définit les droits et obligations des personnes", "Organise la procédure judiciaire", "Règle les relations entre les États", "S'applique uniquement en droit pénal"],
    correctIndex: 1,
    explanation: "Le droit de procédure (ou droit formel) règle la mise en œuvre des droits subjectifs et organise le déroulement des procès ainsi que les voies de recours ; c'est le droit de fond (matériel) qui définit droits et obligations.",
    estimated: false,
  },
  {
    id: "q-bases-08", themeId,
    question: "Quel est le rôle principal du Tribunal fédéral en Suisse ?",
    choices: ["Appliquer les lois cantonales", "Créer de nouvelles lois", "Garantir une application uniforme du droit fédéral", "Gérer les affaires locales"],
    correctIndex: 2,
    explanation: "Le Tribunal fédéral (TF) est la plus haute autorité judiciaire de Suisse ; il garantit une application uniforme du droit fédéral et le respect des droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-bases-09", themeId,
    question: "La jurisprudence est principalement constituée de :",
    choices: ["Décisions rendues par le Parlement", "Décisions rendues par des autorités administratives", "Décisions rendues par les tribunaux", "Lois fédérales"],
    correctIndex: 2,
    explanation: "La jurisprudence est l'ensemble des jugements des tribunaux et des décisions rendues par d'autres autorités investies du pouvoir judiciaire dans un cas d'espèce.",
    estimated: false,
  },
  {
    id: "q-bases-10", themeId,
    question: "Où trouve-t-on la mention des quatre sources du droit suisse ?",
    choices: ["Dans la jurisprudence uniquement", "Dans les traités internationaux", "Dans l'article 1 du Code civil suisse", "Dans l'article 1 du Code des obligations"],
    correctIndex: 2,
    explanation: "L'art. 1 CC mentionne les quatre sources du droit : la loi, la coutume, la jurisprudence et la doctrine.",
    estimated: false,
  },
  {
    id: "q-bases-11", themeId,
    question: "Maxime est arrêté par la police pour conduite en état d'ébriété. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "L'État sanctionne, via le droit pénal, une infraction routière : c'est un rapport vertical entre l'État et un particulier, donc du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-12", themeId,
    question: "Un enseignant renvoie un élève qui adopte un comportement inadéquat en classe. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "L'école est une institution étatique qui exerce une autorité sur l'élève (rapport vertical) : cela relève du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-13", themeId,
    question: "Plusieurs pays ratifient un traité international. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "Un traité entre États règle les relations entre États : cela relève du droit public (droit international public).",
    estimated: false,
  },
  {
    id: "q-bases-14", themeId,
    question: "Par suite du décès de ses parents, Mélanie hérite de leur maison. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 0,
    explanation: "Une succession entre particuliers est un rapport horizontal régi par le droit civil : cela relève du droit privé.",
    estimated: false,
  },
  {
    id: "q-bases-15", themeId,
    question: "Georges doit payer tous les mois son assurance maladie complémentaire. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 0,
    explanation: "L'assurance-maladie complémentaire est un contrat librement conclu avec un assureur privé : cela relève du droit privé, contrairement à l'assurance de base (LAMal) qui relève du droit public.",
    estimated: false,
  },
  {
    id: "q-bases-16", themeId,
    question: "La liberté de la presse est garantie. Cela relève du :",
    choices: ["Droit privé", "Droit public", "Les deux, selon le contexte", "Aucun des deux"],
    correctIndex: 1,
    explanation: "La liberté de la presse est un droit fondamental garanti par la Constitution face à l'État : cela relève du droit public (droit constitutionnel).",
    estimated: false,
  },
  {
    id: "q-bases-17", themeId,
    question: "Les rapports entre individus sont régis en premier lieu, selon l'art. 1 CC, par :",
    choices: ["Le droit public", "Le droit privé", "La coutume", "La jurisprudence"],
    correctIndex: 1,
    explanation: "Les rapports entre particuliers relèvent en premier lieu du droit privé (droit civil, droit des obligations).",
    estimated: false,
  },
  {
    id: "q-bases-18", themeId,
    question: "Une personne privée peut-elle rendre une décision (au sens juridique) ?",
    choices: ["Oui", "Non"],
    correctIndex: 1,
    explanation: "Seule une autorité investie du pouvoir de décision (tribunal, autorité administrative) peut rendre une décision ; un particulier ne le peut pas.",
    estimated: false,
  },
  {
    id: "q-bases-19", themeId,
    question: "Les sources du droit sont, dans l'ordre de l'art. 1 CC :",
    choices: ["Le contrat, la loi, la coutume, l'acte illicite", "L'enrichissement illégitime, la doctrine, la loi, la jurisprudence", "La loi, la coutume, la jurisprudence, la doctrine", "Le contrat, l'enrichissement illégitime, l'acte illicite, la loi"],
    correctIndex: 2,
    explanation: "L'art. 1 CC prévoit, dans cet ordre : la loi (source primaire), puis la coutume, et enfin les solutions consacrées par la doctrine et la jurisprudence.",
    estimated: false,
  },
  {
    id: "q-bases-20", themeId,
    question: "Qui édicte les lois fédérales en Suisse ?",
    choices: ["Les tribunaux", "Le Conseil fédéral", "Le Conseil national et le Conseil d'État", "Le Conseil national et le Conseil des États"],
    correctIndex: 3,
    explanation: "Les lois fédérales sont adoptées par l'Assemblée fédérale, composée du Conseil national et du Conseil des États.",
    estimated: false,
  },
  {
    id: "q-bases-21", themeId,
    question: "Auprès de quel tribunal peut-on porter une affaire si l'on a épuisé toutes les instances en Suisse et que l'on estime que ses droits fondamentaux ont été violés ?",
    choices: ["Le Tribunal fédéral", "Le Tribunal international", "La Cour européenne des droits de l'Homme (CEDH)", "Le Tribunal cantonal de Berne"],
    correctIndex: 2,
    explanation: "Une fois les voies de recours internes épuisées, un recours pour violation des droits fondamentaux peut être porté devant la CEDH.",
    estimated: false,
  },
  {
    id: "q-bases-22", themeId,
    question: "Auprès de quel tribunal porte-t-on une affaire en première instance s'il s'agit d'une infraction visant les intérêts de la Suisse, comme un acte terroriste ?",
    choices: ["Tribunal de police", "Tribunal pénal cantonal", "Tribunal pénal fédéral", "Tribunal fédéral"],
    correctIndex: 2,
    explanation: "Le Tribunal pénal fédéral (TPF), siège à Bellinzone, juge en 1ère instance notamment les infractions visant les intérêts de la Confédération, comme le terrorisme ou le crime organisé.",
    estimated: false,
  },
  {
    id: "q-bases-23", themeId,
    question: "Auprès de quel tribunal porte-t-on une affaire en première instance pour un délit routier mineur ?",
    choices: ["Tribunal pénal fédéral", "Tribunal cantonal", "Tribunal de police", "Tribunal fédéral"],
    correctIndex: 2,
    explanation: "Le tribunal de police, tribunal cantonal de première instance, est compétent pour les délits routiers mineurs.",
    estimated: false,
  },
  {
    id: "q-bases-24", themeId,
    question: "Vers quel tribunal doit-on se tourner en deuxième instance après un jugement du Tribunal de police ?",
    choices: ["Tribunal fédéral", "Tribunal cantonal", "Tribunal administratif fédéral", "Tribunal pénal fédéral"],
    correctIndex: 1,
    explanation: "Le Tribunal cantonal est l'autorité judiciaire cantonale de recours (2e instance) contre les jugements des tribunaux régionaux/de police.",
    estimated: false,
  },
  {
    id: "q-bases-25", themeId,
    question: "Quel tribunal juge en première instance les affaires civiles de faible valeur financière (ex. un litige avec un voisin) ?",
    choices: ["Tribunal régional", "Tribunal administratif fédéral", "Tribunal pénal fédéral", "Tribunal cantonal"],
    correctIndex: 0,
    explanation: "Le tribunal régional (tribunal civil de première instance) juge les litiges civils, y compris de faible valeur, comme un litige de voisinage.",
    estimated: false,
  },
  {
    id: "q-bases-26", themeId,
    question: "Les grandes divisions du droit privé sont :",
    choices: ["Droit administratif, droit civil, droit des obligations et droit commercial", "Droit des obligations, droit de la PI, droit civil et droit pénal", "Droit des obligations, droit de la propriété intellectuelle, droit commercial et droit civil", "Droit pénal, droit civil, droit constitutionnel et droit administratif"],
    correctIndex: 2,
    explanation: "Les grandes divisions du droit privé sont : le droit civil, le droit des obligations, le droit commercial et le droit de la propriété intellectuelle (le droit pénal et le droit administratif relèvent du droit public).",
    estimated: false,
  },
  {
    id: "q-bases-27", themeId,
    question: "Combien de pouvoirs distincts existe-t-il en Suisse (séparation des pouvoirs) ?",
    choices: ["Un", "Deux", "Trois", "Quatre"],
    correctIndex: 2,
    explanation: "La Suisse connaît trois pouvoirs distincts : législatif, exécutif et judiciaire.",
    estimated: false,
  },
  {
    id: "q-bases-28", themeId,
    question: "Où peut-on trouver les textes des lois fédérales en Suisse et comment les consulter ?",
    choices: ["Dans le Registre des sociétés (RS) uniquement", "Dans le Recueil officiel (RO) et le Recueil systématique (RS)", "Dans les journaux locaux", "Dans les archives des cantons uniquement"],
    correctIndex: 1,
    explanation: "Le RO (classé chronologiquement, fait foi) et le RS (classé par domaine, à jour) rassemblent les textes normatifs fédéraux.",
    estimated: false,
  },
  {
    id: "q-bases-29", themeId,
    question: "Qu'est-ce que le droit subjectif ?",
    choices: ["L'ensemble des règles générales et abstraites imposées par une autorité", "Une prérogative accordée à une personne de faire, d'exiger, ou d'être obligée à faire quelque chose", "Uniquement les décisions rendues par les tribunaux", "Uniquement les lois votées par le Parlement"],
    correctIndex: 1,
    explanation: "Le droit subjectif (« mon droit ») est une prérogative accordée à une personne physique ou morale, dictée par le droit objectif ; il se décline en droits, pouvoirs, libertés et obligations.",
    estimated: false,
  },
  {
    id: "q-bases-30", themeId,
    question: "Quelles sont les trois conditions pour qu'une coutume soit reconnue comme source du droit ?",
    choices: ["Être écrite, récente et votée par le peuple", "Être non écrite, née d'un usage durable et implanté, et reconnue par la collectivité comme juridiquement contraignante", "Être approuvée par le Tribunal fédéral, publiée au RO et signée par le Conseil fédéral", "Être appliquée uniquement au niveau international"],
    correctIndex: 1,
    explanation: "La coutume doit être généralement non écrite, être née d'un usage d'une certaine durée qui persiste dans le temps, et être reconnue par la collectivité comme juridiquement obligatoire.",
    estimated: false,
  },
];
