import { QuizQuestion } from "@/models/types";

// ⚠️ CONTENU DÉDUIT (estimated: true) — voir CLAUDE.md avant de modifier.

const themeId = "contrats-informatique";

export const quizContratsInformatique: QuizQuestion[] = [
  {
    id: "q-it-01", themeId,
    question: "Une licence logicielle donne en principe...",
    choices: ["La propriété du code source", "Un droit d'usage, selon des conditions définies", "Un droit de vote dans l'entreprise éditrice", "Un contrat de travail avec l'éditeur"],
    correctIndex: 1,
    explanation: "La licence octroie un droit d'utilisation du logiciel selon des conditions convenues, sans transférer la propriété du code protégé par le droit d'auteur.",
    estimated: true,
  },
  {
    id: "q-it-02", themeId,
    question: "Quelle loi protège un logiciel en tant qu'œuvre ?",
    choices: ["La LPD", "La loi sur le droit d'auteur (LDA)", "Le Code pénal", "La loi sur le travail"],
    correctIndex: 1,
    explanation: "Un logiciel est en principe protégé comme une œuvre au sens de la loi sur le droit d'auteur (LDA), ce qui fonde la nécessité d'une licence pour l'utiliser.",
    estimated: true,
  },
  {
    id: "q-it-03", themeId,
    question: "Un contrat de développement « clé en main », à prix forfaitaire, s'analyse généralement comme...",
    choices: ["Un contrat de travail", "Un contrat d'entreprise (obligation de résultat)", "Un contrat de bail uniquement", "Un mandat pur (obligation de moyens uniquement)"],
    correctIndex: 1,
    explanation: "Lorsqu'un résultat précis est promis contre un prix déterminé, on se rapproche du contrat d'entreprise (art. 363 ss CO), qui impose une obligation de résultat.",
    estimated: true,
  },
  {
    id: "q-it-04", themeId,
    question: "Dans un mandat (art. 394 ss CO), le prestataire doit...",
    choices: ["Garantir un résultat précis dans tous les cas", "Agir avec diligence, sans garantir nécessairement le résultat", "Ne fournir aucune prestation", "Être rémunéré uniquement en cas de succès"],
    correctIndex: 1,
    explanation: "Le mandat impose une obligation de moyens : le prestataire doit agir avec soin et diligence, sans nécessairement garantir un résultat précis.",
    estimated: true,
  },
  {
    id: "q-it-05", themeId,
    question: "Un contrat SaaS combine typiquement plusieurs éléments contractuels, lesquels ?",
    choices: ["Uniquement une vente", "Bail/licence d'usage, mandat (hébergement, maintenance), parfois clauses SLA", "Uniquement un contrat de travail", "Uniquement un contrat de mariage"],
    correctIndex: 1,
    explanation: "Un contrat SaaS mêle souvent mise à disposition de l'usage du logiciel (bail/licence), prestations de service (mandat) et clauses de niveau de service (SLA).",
    estimated: true,
  },
  {
    id: "q-it-06", themeId,
    question: "Que signifie l'acronyme SLA dans un contrat cloud/SaaS ?",
    choices: ["Service Level Agreement (accord sur le niveau de service)", "Software License Authorization", "Secure Login Access", "System Loss Assessment"],
    correctIndex: 0,
    explanation: "Le SLA (Service Level Agreement) définit les engagements du prestataire, notamment en matière de disponibilité et de qualité de service.",
    estimated: true,
  },
  {
    id: "q-it-07", themeId,
    question: "Si une application livrée « clé en main » ne fonctionne pas correctement, le client peut invoquer...",
    choices: ["Uniquement une rupture de contrat de travail", "Les règles sur les défauts de l'ouvrage (contrat d'entreprise)", "Uniquement une plainte pénale", "Aucun recours possible"],
    correctIndex: 1,
    explanation: "Dans un contrat d'entreprise, le client peut invoquer les règles sur la garantie des défauts (réduction du prix, réfection, résolution selon la gravité).",
    estimated: true,
  },
  {
    id: "q-it-08", themeId,
    question: "Pourquoi la localisation et le traitement des données sont-ils des clauses importantes dans un contrat SaaS ?",
    choices: ["Ce n'est jamais pertinent juridiquement", "Car cela touche à la conformité avec la LPD et à la protection des données personnelles", "Uniquement pour des raisons de marketing", "Uniquement si le prestataire est suisse"],
    correctIndex: 1,
    explanation: "Le lieu de traitement et la sous-traitance des données ont un impact direct sur la conformité avec la législation sur la protection des données (LPD).",
    estimated: true,
  },
  {
    id: "q-it-09", themeId,
    question: "Une entreprise qui achète simplement une licence n'a en principe pas le droit de...",
    choices: ["Utiliser le logiciel selon les conditions convenues", "Modifier et redistribuer librement le code source, sauf autorisation contraire", "Installer le logiciel sur le nombre de postes prévu", "Bénéficier du support si prévu au contrat"],
    correctIndex: 1,
    explanation: "Sans autorisation explicite (licence open source ou clause spécifique), le titulaire d'une licence classique n'a pas le droit de modifier ou redistribuer librement le code protégé.",
    estimated: true,
  },
  {
    id: "q-it-10", themeId,
    question: "Un contrat de maintenance informatique s'apparente généralement à...",
    choices: ["Un contrat de vente unique", "Un mandat ou un contrat d'entreprise selon les prestations exactes promises", "Un contrat de travail avec l'entreprise cliente", "Une donation"],
    correctIndex: 1,
    explanation: "Selon que la maintenance porte sur des interventions ponctuelles diligentes (mandat) ou un résultat précis garanti (entreprise), la qualification varie selon les termes du contrat.",
    estimated: true,
  },
  {
    id: "q-it-11", themeId,
    question: "L'obligation de résultat, propre au contrat d'entreprise, signifie que le prestataire...",
    choices: ["Doit seulement faire de son mieux, sans garantie", "S'engage à livrer un ouvrage conforme au résultat promis", "N'a aucune obligation contractuelle", "Doit uniquement respecter des délais, peu importe la qualité"],
    correctIndex: 1,
    explanation: "L'obligation de résultat engage le prestataire sur l'atteinte effective du résultat convenu (ex. un logiciel qui fonctionne comme spécifié), et pas seulement sur ses efforts.",
    estimated: true,
  },
  {
    id: "q-it-12", themeId,
    question: "Une clause de propriété intellectuelle dans un contrat de développement sur mesure sert notamment à...",
    choices: ["Interdire tout usage du logiciel par le client", "Préciser qui détient les droits sur le code développé (client, prestataire, ou partage)", "Fixer uniquement le prix du contrat", "Remplacer le besoin d'une licence"],
    correctIndex: 1,
    explanation: "Cette clause détermine à qui appartiennent les droits sur le code créé sur mesure, un point souvent négocié et pas automatique par défaut.",
    estimated: true,
  },
  {
    id: "q-it-13", themeId,
    question: "Le paiement d'un abonnement mensuel pour accéder à un logiciel en ligne évoque en premier lieu...",
    choices: ["Un contrat de donation", "Un élément de type bail/licence d'usage périodique", "Un contrat de travail", "Un contrat de cautionnement"],
    correctIndex: 1,
    explanation: "Le paiement périodique pour un droit d'usage temporaire évoque la logique du bail ou de la licence renouvelée, typique des modèles SaaS.",
    estimated: true,
  },
  {
    id: "q-it-14", themeId,
    question: "En cas de litige sur un contrat de prestations IT, la première étape d'analyse consiste souvent à...",
    choices: ["Ignorer le contrat et appliquer directement la loi pénale", "Qualifier le contrat (vente, mandat, entreprise, mixte) pour savoir quelles règles du CO s'appliquent", "Résilier automatiquement tout contrat en cours", "Considérer que seul le droit du travail s'applique"],
    correctIndex: 1,
    explanation: "Qualifier correctement le contrat est essentiel car les règles applicables (obligation de moyens ou de résultat, garanties, délais) diffèrent selon le type de contrat retenu.",
    estimated: true,
  },
  {
    id: "q-it-15", themeId,
    question: "Un contrat mixte, comme un contrat SaaS, est soumis à...",
    choices: ["Aucune règle légale, seul le contrat compte", "Un mélange des règles applicables à chacun des types de contrat qui le composent", "Uniquement les règles de la vente", "Uniquement les règles du droit pénal"],
    correctIndex: 1,
    explanation: "Face à un contrat mixte, on applique en général les règles correspondant à chaque élément (bail, mandat, licence) selon la nature de la prestation concernée, en tenant compte de la volonté des parties.",
    estimated: true,
  },
];
