import { QuizQuestion } from "@/models/types";

// ⚠️ CONTENU DÉDUIT (estimated: true) — voir CLAUDE.md avant de modifier.

const themeId = "contrat-travail";

export const quizContratTravail: QuizQuestion[] = [
  {
    id: "q-tr-01", themeId,
    question: "Quel article du CO définit le contrat de travail ?",
    choices: ["Art. 28 CO", "Art. 319 CO", "Art. 1 CO", "Art. 97 CO"],
    correctIndex: 1,
    explanation: "L'art. 319 CO définit le contrat de travail individuel comme l'engagement à travailler, contre salaire, sous la direction de l'employeur.",
    estimated: true,
  },
  {
    id: "q-tr-02", themeId,
    question: "Quel est le critère déterminant pour distinguer contrat de travail et mandat ?",
    choices: ["Le montant de la rémunération", "Le lien de subordination", "Le lieu où le travail est effectué", "La nationalité du travailleur"],
    correctIndex: 1,
    explanation: "Le lien de subordination (directives, contrôle, horaires imposés) est le critère central du contrat de travail, absent en principe dans un mandat.",
    estimated: true,
  },
  {
    id: "q-tr-03", themeId,
    question: "Que doit protéger l'employeur selon l'art. 328 CO ?",
    choices: ["Uniquement le matériel de l'entreprise", "La santé et la personnalité du travailleur", "Uniquement les données financières", "Uniquement le secret des affaires"],
    correctIndex: 1,
    explanation: "L'art. 328 CO impose à l'employeur de protéger et respecter la personnalité et la santé du travailleur dans les rapports de travail.",
    estimated: true,
  },
  {
    id: "q-tr-04", themeId,
    question: "Le devoir de fidélité du travailleur implique notamment...",
    choices: ["De ne jamais prendre de vacances", "De ne pas concurrencer ou nuire aux intérêts légitimes de l'employeur", "De travailler gratuitement en cas de difficulté financière de l'entreprise", "De signer tout document sans le lire"],
    correctIndex: 1,
    explanation: "Le devoir de fidélité oblige le travailleur à sauvegarder les intérêts légitimes de son employeur, notamment en évitant les activités concurrentes déloyales.",
    estimated: true,
  },
  {
    id: "q-tr-05", themeId,
    question: "Un congé abusif au sens de l'art. 336 CO a pour conséquence...",
    choices: ["Que le contrat continue automatiquement", "Que le congé reste valable mais peut donner droit à une indemnité", "Que l'employeur va en prison automatiquement", "Que le travailleur perd tous ses droits"],
    correctIndex: 1,
    explanation: "En Suisse, la liberté de résiliation prévaut : un congé abusif met quand même fin au contrat, mais ouvre le droit à une indemnité (jusqu'à 6 mois de salaire, art. 336a CO).",
    estimated: true,
  },
  {
    id: "q-tr-06", themeId,
    question: "Un CDD (contrat à durée déterminée) prend fin, en principe...",
    choices: ["Uniquement par un licenciement formel", "Automatiquement à l'échéance convenue, sans congé nécessaire", "Jamais avant 5 ans", "Uniquement par accord du syndicat"],
    correctIndex: 1,
    explanation: "Le CDD prend fin de plein droit à l'échéance du terme convenu, sans qu'un congé ne soit nécessaire, sauf clause de renouvellement tacite.",
    estimated: true,
  },
  {
    id: "q-tr-07", themeId,
    question: "Quel élément n'est PAS caractéristique du contrat de travail ?",
    choices: ["Une prestation de travail", "Une rémunération", "Un lien de subordination", "L'absence totale de durée déterminable"],
    correctIndex: 3,
    explanation: "Le contrat de travail comporte prestation de travail, rémunération, subordination et s'inscrit dans une certaine durée ; l'absence de durée n'est pas un critère du contrat de travail.",
    estimated: true,
  },
  {
    id: "q-tr-08", themeId,
    question: "Une développeuse facturée « à l'heure » mais soumise à des horaires stricts et un contrôle constant relève probablement...",
    choices: ["D'un contrat de vente", "D'un contrat de travail, malgré l'intitulé de facturation", "D'un contrat de bail", "D'aucune qualification juridique"],
    correctIndex: 1,
    explanation: "La qualification réelle prime sur l'intitulé donné par les parties : un fort lien de subordination pointe vers un contrat de travail, même si la forme de facturation évoque l'indépendance.",
    estimated: true,
  },
  {
    id: "q-tr-09", themeId,
    question: "Le certificat de travail, sur demande du travailleur, doit être...",
    choices: ["Toujours défavorable", "Véridique et complet, sans porter préjudice indûment au travailleur", "Facultatif dans tous les cas", "Rédigé uniquement par un avocat"],
    correctIndex: 1,
    explanation: "Le certificat de travail doit refléter fidèlement la réalité, tout en étant formulé de façon à ne pas nuire indûment aux perspectives professionnelles du travailleur.",
    estimated: true,
  },
  {
    id: "q-tr-10", themeId,
    question: "En cas de congé donné pendant une incapacité de travail (maladie), la loi prévoit...",
    choices: ["Aucune protection particulière", "Une protection contre le congé pendant une période déterminée (temps inopportun)", "Que le contrat se poursuit indéfiniment", "Que l'employeur doit payer le salaire à vie"],
    correctIndex: 1,
    explanation: "Le CO protège le travailleur contre un congé donné en temps inopportun (ex. pendant une incapacité de travail), pendant des délais définis selon l'ancienneté (art. 336c CO).",
    estimated: true,
  },
  {
    id: "q-tr-11", themeId,
    question: "Qui dirige et contrôle le travail dans un contrat de travail ?",
    choices: ["Le travailleur lui-même, en toute indépendance", "L'employeur, dans le cadre du lien de subordination", "Un tiers extérieur au contrat", "Personne, c'est laissé libre"],
    correctIndex: 1,
    explanation: "C'est précisément l'exercice d'un pouvoir de direction et de contrôle par l'employeur qui caractérise la subordination propre au contrat de travail.",
    estimated: true,
  },
  {
    id: "q-tr-12", themeId,
    question: "Un employeur peut-il librement résilier un contrat de travail à durée indéterminée ?",
    choices: ["Non, jamais sans motif", "Oui, en respectant le délai de congé, sous réserve des règles sur le congé abusif ou en temps inopportun", "Oui, sans aucun délai à respecter", "Non, il faut l'accord du travailleur"],
    correctIndex: 1,
    explanation: "Le droit suisse connaît la liberté de résiliation : l'employeur (ou le travailleur) peut résilier en respectant le délai de congé, sous réserve des protections contre le congé abusif ou en temps inopportun.",
    estimated: true,
  },
  {
    id: "q-tr-13", themeId,
    question: "Quel type de contrat s'applique typiquement à un consultant indépendant sans lien de subordination ?",
    choices: ["Contrat de travail", "Mandat (ou contrat d'entreprise selon le cas)", "Bail à loyer", "Contrat de mariage"],
    correctIndex: 1,
    explanation: "En l'absence de subordination, la relation s'analyse plutôt comme un mandat (obligation de moyens) ou un contrat d'entreprise (obligation de résultat), selon ce qui est promis.",
    estimated: true,
  },
  {
    id: "q-tr-14", themeId,
    question: "L'obligation de payer le salaire convenu incombe...",
    choices: ["Au travailleur", "À l'employeur", "À l'État", "À un tiers"],
    correctIndex: 1,
    explanation: "Le versement du salaire convenu est l'obligation centrale de l'employeur en contrepartie de la prestation de travail.",
    estimated: true,
  },
  {
    id: "q-tr-15", themeId,
    question: "Un motif de congé fondé sur l'exercice de bonne foi d'un droit par le travailleur (ex. signaler une irrégularité) est un exemple typique de...",
    choices: ["Congé parfaitement normal et sans conséquence", "Congé potentiellement abusif au sens de l'art. 336 CO", "Motif obligatoire de licenciement immédiat", "Motif qui rend le contrat nul dès l'origine"],
    correctIndex: 1,
    explanation: "L'art. 336 CO liste des exemples de motifs abusifs, dont le congé donné en raison de l'exercice de bonne foi d'une prétention légitime par le travailleur.",
    estimated: true,
  },
];
