import { QuizQuestion } from "@/models/types";

// Contenu réel (estimated: false) — Chapitre 2 "Droit constitutionnel et
// droits fondamentaux" (support de cours PGD IG 26/27).

const themeId = "droit-constitutionnel";

export const quizDroitConstitutionnel: QuizQuestion[] = [
  {
    id: "q-const-01", themeId,
    question: "Quels sont les trois éléments constitutifs de l'État ?",
    choices: ["Population, territoire, souveraineté", "Gouvernement, parlement, tribunaux", "Peuple, cantons, communes", "Constitution, lois, ordonnances"],
    correctIndex: 0,
    explanation: "L'État se compose d'une population, d'un territoire et de la souveraineté (autorité détentrice de la force publique étatique).",
    estimated: false,
  },
  {
    id: "q-const-02", themeId,
    question: "Dans quels articles de la Constitution fédérale est défini l'État moderne suisse ?",
    choices: ["Art. 7 à 36", "Art. 1 à 5", "Art. 143 à 173", "Art. 192 à 196"],
    correctIndex: 1,
    explanation: "Le cours situe l'État moderne suisse aux art. 1 à 5 Cst. (Titre 1, dispositions générales : art. 1-6).",
    estimated: false,
  },
  {
    id: "q-const-03", themeId,
    question: "La Constitution (au sens formel) se distingue d'une loi ordinaire par :",
    choices: ["Son auteur uniquement", "Sa date d'entrée en vigueur", "Son objet, sa portée et sa procédure de confection", "Son absence de sanction"],
    correctIndex: 2,
    explanation: "La Cst. est une loi au sens formel édictée par le pouvoir constituant ; elle se distingue d'une loi ordinaire par son objet, sa portée et sa procédure de confection.",
    estimated: false,
  },
  {
    id: "q-const-04", themeId,
    question: "Parmi les propositions suivantes, laquelle n'est PAS un rôle de la Constitution selon le cours ?",
    choices: ["Loi fondamentale", "Limitation du pouvoir", "Expression de la volonté commune", "Juger les litiges entre particuliers"],
    correctIndex: 3,
    explanation: "Les trois rôles vus en cours sont : loi fondamentale, limitation du pouvoir (séparation des pouvoirs) et expression de la volonté commune (votée par le peuple). Juger relève des tribunaux.",
    estimated: false,
  },
  {
    id: "q-const-05", themeId,
    question: "Le droit constitutionnel est une discipline de :",
    choices: ["Droit privé", "Droit public", "Droit international uniquement", "Droit pénal"],
    correctIndex: 1,
    explanation: "Le droit constitutionnel est une discipline de droit public (relation État-citoyens).",
    estimated: false,
  },
  {
    id: "q-const-06", themeId,
    question: "Quelle est la seule source du droit constitutionnel au sens formel ?",
    choices: ["La loi sur le TF", "Les constitutions cantonales", "La Constitution", "Le droit international"],
    correctIndex: 2,
    explanation: "Au sens formel, la source est la Constitution (le texte). Les lois citées, les constitutions cantonales et le droit international sont des sources au sens matériel.",
    estimated: false,
  },
  {
    id: "q-const-07", themeId,
    question: "Quels sont les trois piliers du droit constitutionnel vus en cours ?",
    choices: ["Loi, coutume, jurisprudence", "Législatif, exécutif, judiciaire", "Fédéralisme, démocratie, droits fondamentaux", "Population, territoire, souveraineté"],
    correctIndex: 2,
    explanation: "Les piliers sont le fédéralisme (structure de l'État), la démocratie (représentative, directe / semi-directe) et les droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-const-08", themeId,
    question: "La Constitution fédérale de 1999 se compose de combien de titres ?",
    choices: ["Quatre", "Cinq", "Six", "Sept"],
    correctIndex: 2,
    explanation: "Elle comprend six titres, des dispositions générales (art. 1-6) à la révision de la Constitution et dispositions transitoires (art. 192-196).",
    estimated: false,
  },
  {
    id: "q-const-09", themeId,
    question: "Dans quel titre de la Cst. se trouvent les droits fondamentaux, la citoyenneté et les buts sociaux ?",
    choices: ["Titre 1 (art. 1-6)", "Titre 2 (art. 7-41)", "Titre 3 (art. 42-135)", "Titre 5 (art. 173-191)"],
    correctIndex: 1,
    explanation: "Le Titre 2 (art. 7-41) traite des droits fondamentaux, de la citoyenneté et des buts sociaux.",
    estimated: false,
  },
  {
    id: "q-const-10", themeId,
    question: "Dans quel titre de la Cst. se trouvent les autorités fédérales ?",
    choices: ["Titre 5 (art. 173-191)", "Titre 4 (art. 136-142)", "Titre 3 (art. 42-135)", "Titre 6 (art. 192-196)"],
    correctIndex: 0,
    explanation: "Le Titre 5 (art. 173-191) traite des autorités fédérales ; le Titre 4 (art. 136-142) du peuple et des cantons.",
    estimated: false,
  },
  {
    id: "q-const-11", themeId,
    question: "Que prévoit l'art. 5 al. 4 Cst. ?",
    choices: ["Le TF applique les lois fédérales", "La Confédération et les cantons respectent le droit international (primauté)", "Les cantons sont souverains", "Le Conseil fédéral compte 7 membres"],
    correctIndex: 1,
    explanation: "L'art. 5 al. 4 Cst. pose la primauté du droit international : la Confédération et les cantons le respectent.",
    estimated: false,
  },
  {
    id: "q-const-12", themeId,
    question: "Que prévoit l'art. 190 Cst. ?",
    choices: ["Le TF et les autres autorités appliquent les lois fédérales et le droit international (incorporation)", "Les droits fondamentaux sont inviolables", "Les cantons sont des États fédérés", "Le peuple vote la Constitution"],
    correctIndex: 0,
    explanation: "L'art. 190 Cst. oblige le Tribunal fédéral et les autres autorités à appliquer les lois fédérales et le droit international : c'est l'incorporation du droit international.",
    estimated: false,
  },
  {
    id: "q-const-13", themeId,
    question: "Qu'est-ce qu'un traité international ?",
    choices: ["Une loi cantonale", "Un contrat entre deux ou plusieurs sujets de droit international qui créent des règles de droit", "Une décision du Tribunal fédéral", "Un accord entre deux communes"],
    correctIndex: 1,
    explanation: "Un traité international (aussi appelé convention internationale) est un contrat entre sujets de droit international qui créent des règles de droit.",
    estimated: false,
  },
  {
    id: "q-const-14", themeId,
    question: "Combien de cantons (y compris les demi-cantons) compte la Suisse ?",
    choices: ["20", "23", "26", "29"],
    correctIndex: 2,
    explanation: "La Confédération helvétique compte 26 cantons (dont des demi-cantons), qui sont des États fédérés.",
    estimated: false,
  },
  {
    id: "q-const-15", themeId,
    question: "Qui forme le pouvoir constituant suisse ?",
    choices: ["Le Conseil fédéral seul", "Les cantons et le peuple", "Le Tribunal fédéral", "L'Assemblée fédérale seule"],
    correctIndex: 1,
    explanation: "Selon le cours, le pouvoir constituant CH = cantons + peuple.",
    estimated: false,
  },
  {
    id: "q-const-16", themeId,
    question: "Dans un État fédéral comme la Suisse, les cantons sont souverains :",
    choices: ["Dans tous les domaines sans exception", "Uniquement en matière pénale", "Tant que leur compétence n'est pas limitée par la Constitution fédérale", "Jamais"],
    correctIndex: 2,
    explanation: "La Constitution définit les domaines de compétence ; les cantons sont souverains tant que leur compétence n'est pas limitée par la Cst.",
    estimated: false,
  },
  {
    id: "q-const-17", themeId,
    question: "Quels sont les trois niveaux juridiques en Suisse ?",
    choices: ["Fédéral, cantonal, communal", "National, régional, local", "Fédéral, international, communal", "Cantonal, intercantonal, européen"],
    correctIndex: 0,
    explanation: "Le droit se décline en trois niveaux : fédéral, cantonal et communal.",
    estimated: false,
  },
  {
    id: "q-const-18", themeId,
    question: "Quel est le principe de la séparation des pouvoirs ?",
    choices: ["Un seul organe exerce toutes les fonctions de l'État", "Les diverses fonctions de l'État sont dévolues à des organes distincts et indépendants", "Les cantons et la Confédération se partagent le pouvoir judiciaire", "Le peuple exerce seul le pouvoir législatif"],
    correctIndex: 1,
    explanation: "Les fonctions de l'État (législatif, exécutif, judiciaire) doivent être confiées à des organes distincts et indépendants.",
    estimated: false,
  },
  {
    id: "q-const-19", themeId,
    question: "Quel organe exerce le pouvoir législatif au niveau fédéral ?",
    choices: ["Le Conseil fédéral", "Le Tribunal fédéral", "L'Assemblée fédérale", "La Conférence des cantons"],
    correctIndex: 2,
    explanation: "Le pouvoir législatif fédéral est exercé par l'Assemblée fédérale (art. 143 à 173 et 179 Cst.).",
    estimated: false,
  },
  {
    id: "q-const-20", themeId,
    question: "Que signifie « système bicaméral » ?",
    choices: ["Deux Chambres se partagent le même pouvoir, traitent les mêmes affaires et siègent séparément", "Deux gouvernements coexistent", "Il y a deux tribunaux suprêmes", "Le Parlement siège deux fois par an"],
    correctIndex: 0,
    explanation: "L'Assemblée fédérale est bicamérale : Conseil national et Conseil des États partagent le même pouvoir et siègent séparément.",
    estimated: false,
  },
  {
    id: "q-const-21", themeId,
    question: "Quelle Chambre représente les cantons ?",
    choices: ["Le Conseil national", "Le Conseil fédéral", "Le Conseil des États (Chambre haute)", "Le Grand conseil"],
    correctIndex: 2,
    explanation: "Le Conseil national est la Chambre du peuple ; le Conseil des États (Chambre haute) est la Chambre des cantons.",
    estimated: false,
  },
  {
    id: "q-const-22", themeId,
    question: "Comment s'appelle le pouvoir législatif au niveau cantonal et au niveau communal ?",
    choices: ["Conseil d'État / Conseil communal", "Parlement ou Grand conseil / Conseil général ou assemblée communale", "Tribunal cantonal / Tribunal communal", "Conseil national / Conseil général"],
    correctIndex: 1,
    explanation: "Cantonal : Parlement / Grand conseil. Communal : Conseil général ou assemblée communale.",
    estimated: false,
  },
  {
    id: "q-const-23", themeId,
    question: "Combien de conseillers fédéraux compte le Conseil fédéral et pour quelle durée sont-ils élus ?",
    choices: ["5 membres, 6 ans", "7 membres, 4 ans", "9 membres, 4 ans", "7 membres, 1 an"],
    correctIndex: 1,
    explanation: "7 conseillers fédéraux sont élus tous les 4 ans par l'Assemblée fédérale ; le Président est élu pour une année.",
    estimated: false,
  },
  {
    id: "q-const-24", themeId,
    question: "Qui élit les conseillers fédéraux ?",
    choices: ["Le peuple", "Les cantons", "Le Tribunal fédéral", "L'Assemblée fédérale"],
    correctIndex: 3,
    explanation: "Les 7 conseillers fédéraux sont élus par l'Assemblée fédérale.",
    estimated: false,
  },
  {
    id: "q-const-25", themeId,
    question: "Que signifie le principe de collégialité du Conseil fédéral ?",
    choices: ["Chaque conseiller décide seul dans son domaine", "L'autorité exécutive agit collectivement ; ses débats ne sont pas publics", "Les débats sont publics et télévisés", "Le Président tranche seul"],
    correctIndex: 1,
    explanation: "L'exécutif fonctionne de manière permanente, ses débats ne sont pas publics et il agit de manière collégiale.",
    estimated: false,
  },
  {
    id: "q-const-26", themeId,
    question: "Quel est l'organe exécutif au niveau cantonal et communal ?",
    choices: ["Gouvernement / Conseil d'État ; Conseil communal", "Grand conseil ; Conseil général", "Tribunal cantonal ; Tribunal communal", "Conseil des États ; Conseil national"],
    correctIndex: 0,
    explanation: "Cantonal : Gouvernement / Conseil d'État. Communal : Conseil communal.",
    estimated: false,
  },
  {
    id: "q-const-27", themeId,
    question: "Contre qui les droits fondamentaux sont-ils dirigés (destinataire) ?",
    choices: ["Contre les particuliers", "Contre l'État ou une autorité disposant de la puissance publique", "Contre les entreprises uniquement", "Contre les étrangers"],
    correctIndex: 1,
    explanation: "Les individus sont les bénéficiaires ; le destinataire est l'État ou une autorité disposant de la puissance publique, qui doit les respecter.",
    estimated: false,
  },
  {
    id: "q-const-28", themeId,
    question: "Quelles sont les sources des droits fondamentaux citées en cours ?",
    choices: ["Uniquement la Cst. fédérale", "Cst. fédérale, constitutions cantonales, CEDH et Pacte ONU II", "Uniquement le Code civil", "Cst. fédérale et jurisprudence cantonale seulement"],
    correctIndex: 1,
    explanation: "Sources : Constitution fédérale (art. 7 à 36), constitutions cantonales, Convention européenne des droits de l'homme et Pacte international relatif aux droits civils et politiques (Pacte ONU II).",
    estimated: false,
  },
  {
    id: "q-const-29", themeId,
    question: "Quel article de la Cst. fixe les conditions de restriction des droits fondamentaux ?",
    choices: ["Art. 5", "Art. 10", "Art. 36", "Art. 190"],
    correctIndex: 2,
    explanation: "L'art. 36 Cst. (Restriction des droits fondamentaux) fixe 4 conditions très restrictives.",
    estimated: false,
  },
  {
    id: "q-const-30", themeId,
    question: "Quelles sont les 4 conditions de l'art. 36 Cst. ?",
    choices: ["Base légale, intérêt public, proportionnalité, respect de l'essence du droit", "Loi, coutume, jurisprudence, doctrine", "Population, territoire, souveraineté, droit", "Base légale, urgence, gratuité, publicité"],
    correctIndex: 0,
    explanation: "Base légale (al. 1), intérêt public ou protection d'un droit fondamental d'autrui (al. 2), proportionnalité (al. 3) et essence inviolable (al. 4).",
    estimated: false,
  },
  {
    id: "q-const-31", themeId,
    question: "Selon l'art. 36 al. 1 Cst., quelles restrictions doivent être prévues par une loi ?",
    choices: ["Toutes les restrictions, même légères", "Les restrictions graves", "Aucune, une ordonnance suffit toujours", "Seulement celles en temps de guerre"],
    correctIndex: 1,
    explanation: "Toute restriction doit avoir une base légale ; les restrictions graves doivent être prévues par une loi. Les cas de danger sérieux, direct et imminent sont réservés.",
    estimated: false,
  },
  {
    id: "q-const-32", themeId,
    question: "Pourquoi exige-t-on une base légale pour restreindre un droit fondamental ?",
    choices: ["Pour garantir la sécurité et la prévisibilité du droit, l'égalité de traitement et la séparation des pouvoirs", "Pour augmenter les impôts", "Pour accélérer les procès", "Pour éviter l'intervention des tribunaux"],
    correctIndex: 0,
    explanation: "La base légale garantit sécurité et prévisibilité, égalité de traitement et séparation des pouvoirs ; la base légale formelle permet le contrôle de la démocratie directe.",
    estimated: false,
  },
  {
    id: "q-const-33", themeId,
    question: "L'intérêt public qui justifie une restriction vise à maintenir l'ordre public, soit :",
    choices: ["La sécurité, la santé, la tranquillité", "La richesse, la réputation, la tradition", "La langue, la religion, la culture", "Le profit, la concurrence, la croissance"],
    correctIndex: 0,
    explanation: "Sécurité (ex. pas de publicité le long des autoroutes), santé (ex. vente de médicaments en ligne), tranquillité (ex. parcours d'une manifestation).",
    estimated: false,
  },
  {
    id: "q-const-34", themeId,
    question: "Que signifie le principe de proportionnalité ?",
    choices: ["L'État peut utiliser n'importe quel moyen s'il poursuit un intérêt public", "L'État limite la restriction d'un droit fondamental au strict nécessaire", "Les droits fondamentaux sont répartis proportionnellement aux cantons", "L'État doit appliquer le scrutin proportionnel"],
    correctIndex: 1,
    explanation: "La poursuite d'un intérêt public légitime ne permet pas n'importe quel moyen : la restriction doit se limiter au strict nécessaire.",
    estimated: false,
  },
  {
    id: "q-const-35", themeId,
    question: "L'interdiction de la peine de mort est une application de quel droit ?",
    choices: ["Liberté de la presse", "Liberté personnelle (art. 10 Cst.), protection de la vie", "Liberté de réunion", "Garantie de la propriété"],
    correctIndex: 1,
    explanation: "L'art. 10 Cst. protège la vie : la peine de mort est interdite.",
    estimated: false,
  },
  {
    id: "q-const-36", themeId,
    question: "Le consentement du patient pour un acte opératoire relève de :",
    choices: ["L'intégrité physique (art. 10 Cst.)", "La liberté de la science", "La liberté de mouvement", "Le droit de pétition"],
    correctIndex: 0,
    explanation: "Le cours cite le consentement du patient pour un acte opératoire comme exemple de protection de l'intégrité physique.",
    estimated: false,
  },
  {
    id: "q-const-37", themeId,
    question: "La détention préventive est donnée en exemple négatif de quelle liberté ?",
    choices: ["Liberté d'opinion", "Liberté de mouvement (liberté d'aller et de venir)", "Liberté de l'art", "Liberté syndicale"],
    correctIndex: 1,
    explanation: "La liberté de mouvement (art. 10 Cst.) est la liberté d'aller et de venir ; la détention préventive en est l'exemple négatif.",
    estimated: false,
  },
  {
    id: "q-const-38", themeId,
    question: "Que protège la vie privée (art. 10 Cst.) selon le cours ?",
    choices: ["La sphère privée et intime, les relations personnelles et familiales, l'honneur et la réputation", "Uniquement le domicile", "Les biens immobiliers", "Les contrats conclus"],
    correctIndex: 0,
    explanation: "La vie privée couvre la sphère privée et intime, les relations personnelles et familiales, l'honneur et la réputation.",
    estimated: false,
  },
  {
    id: "q-const-39", themeId,
    question: "Quelle liberté de communication protège l'enseignement et la recherche ?",
    choices: ["La liberté de la presse", "La liberté de l'art", "La liberté de la science", "La liberté de réunion"],
    correctIndex: 2,
    explanation: "Liberté de la science = enseignement et recherche ; liberté de l'art = création et expression artistiques ; liberté de la presse ou des médias = communication.",
    estimated: false,
  },
  {
    id: "q-const-40", themeId,
    question: "Parmi les suivantes, laquelle fait partie des libertés de communication (art. 16, 17, 20-23, 33 Cst.) ?",
    choices: ["Le droit de pétition", "La garantie de la propriété", "La liberté économique", "Le droit à la vie"],
    correctIndex: 0,
    explanation: "Les libertés de communication incluent : opinion et expression, presse et médias, science, art, réunion, association et droit de pétition.",
    estimated: false,
  },
  {
    id: "q-const-41", themeId,
    question: "Parmi les suivantes, laquelle est une source du droit constitutionnel au sens matériel ?",
    choices: ["La loi fédérale sur les droits politiques", "Le Code des obligations", "Le règlement communal", "Une ordonnance du Conseil fédéral sur les loyers"],
    correctIndex: 0,
    explanation: "Sources au sens matériel : loi sur les droits politiques, loi sur l'Assemblée fédérale, loi sur l'organisation du gouvernement et de l'administration, loi sur le TF, constitutions cantonales, droit international.",
    estimated: false,
  },
  {
    id: "q-const-42", themeId,
    question: "La Suisse est :",
    choices: ["Un État unitaire", "Un État fédéral (Confédération + cantons)", "Une monarchie", "Une démocratie uniquement représentative"],
    correctIndex: 1,
    explanation: "La CH est un État fédéral, les cantons sont des États fédérés ; la démocratie est représentative et directe / semi-directe.",
    estimated: false,
  },
  {
    id: "q-const-43", themeId,
    question: "Qu'est-ce que la souveraineté ?",
    choices: ["Le territoire de l'État", "La population de l'État", "L'autorité détentrice de la force publique étatique", "Le droit de vote"],
    correctIndex: 2,
    explanation: "Troisième élément constitutif de l'État.",
    estimated: false,
  },
  {
    id: "q-const-44", themeId,
    question: "Quelle opposition de structures d'État est évoquée ?",
    choices: ["Monarchie et république", "État unitaire et État fédéral", "Droit privé et droit public", "Droit interne et externe"],
    correctIndex: 1,
    explanation: "On oppose l'État unitaire à l'État fédéral.",
    estimated: false,
  },
  {
    id: "q-const-45", themeId,
    question: "Qui édicte la Constitution (au sens formel) ?",
    choices: ["Le pouvoir constituant", "Le Conseil fédéral", "Le Tribunal fédéral", "Les communes"],
    correctIndex: 0,
    explanation: "C'est la loi fondamentale édictée par le pouvoir constituant.",
    estimated: false,
  },
  {
    id: "q-const-46", themeId,
    question: "La Constitution fédérale est-elle votée par le peuple ?",
    choices: ["Non, par le Conseil fédéral seul", "Non, par le TF", "Non, par les communes", "Oui (expression de la volonté commune)"],
    correctIndex: 3,
    explanation: "Rôle : expression de la volonté commune.",
    estimated: false,
  },
  {
    id: "q-const-47", themeId,
    question: "« Limitation du pouvoir » : par quel moyen la Constitution limite-t-elle le pouvoir ?",
    choices: ["Des sanctions pénales", "L'abolition de l'État", "Ses règles d'organisation de l'État, notamment la séparation des pouvoirs", "Le vote du budget"],
    correctIndex: 2,
    explanation: "Un des trois rôles de la Constitution.",
    estimated: false,
  },
  {
    id: "q-const-48", themeId,
    question: "La Constitution « loi fondamentale » contient :",
    choices: ["Uniquement des règles de procédure", "Les règles cardinales de l'État et les droits fondamentaux", "Les jugements du TF", "Les contrats de droit privé"],
    correctIndex: 1,
    explanation: "Rôle de loi fondamentale.",
    estimated: false,
  },
  {
    id: "q-const-49", themeId,
    question: "Le droit constitutionnel au sens formel est :",
    choices: ["Le texte de la Constitution", "Toutes les lois fédérales", "La jurisprudence du TF", "Le droit cantonal uniquement"],
    correctIndex: 0,
    explanation: "Au sens formel = texte de la Cst. ; au sens matériel = règles fondamentales supérieures aux autres.",
    estimated: false,
  },
  {
    id: "q-const-50", themeId,
    question: "Le droit constitutionnel au sens matériel est :",
    choices: ["Uniquement la Cst. de 1999", "Les règles de procédure civile", "Les coutumes locales", "L'ensemble des règles juridiques fondamentales relatives à un État, à son organisation et à son fonctionnement"],
    correctIndex: 3,
    explanation: "Règles supérieures aux autres visant l'organisation et le fonctionnement de l'État.",
    estimated: false,
  },
  {
    id: "q-const-51", themeId,
    question: "Quelle loi N'est PAS citée comme source du droit constitutionnel au sens matériel ?",
    choices: ["La loi fédérale sur les droits politiques", "La loi sur l'Assemblée fédérale", "Le Code des obligations", "La loi sur le TF"],
    correctIndex: 2,
    explanation: "Sont citées : droits politiques, Assemblée fédérale, organisation du gouvernement et de l'administration, TF, constitutions cantonales, droit international.",
    estimated: false,
  },
  {
    id: "q-const-52", themeId,
    question: "Les constitutions cantonales sont des sources du droit constitutionnel :",
    choices: ["Au sens formel uniquement", "Au sens matériel", "Elles ne sont pas des sources", "Au sens international"],
    correctIndex: 1,
    explanation: "Avec le droit international et plusieurs lois fédérales.",
    estimated: false,
  },
  {
    id: "q-const-53", themeId,
    question: "La démocratie suisse est :",
    choices: ["Représentative et directe / semi-directe", "Uniquement représentative", "Uniquement directe", "Une monarchie constitutionnelle"],
    correctIndex: 0,
    explanation: "Deuxième pilier du droit constitutionnel.",
    estimated: false,
  },
  {
    id: "q-const-54", themeId,
    question: "Dans l'État fédéral suisse, que sont les cantons ?",
    choices: ["Des communes", "Des organes de la Confédération", "Des tribunaux", "Des États fédérés"],
    correctIndex: 3,
    explanation: "La CH (Confédération + cantons) est un État fédéral ; les cantons sont des États fédérés.",
    estimated: false,
  },
  {
    id: "q-const-55", themeId,
    question: "Quels sont les art. du Titre 1 de la Cst. ?",
    choices: ["Art. 7 à 41", "Art. 42 à 135", "Art. 1 à 6 : dispositions générales", "Art. 173 à 191"],
    correctIndex: 2,
    explanation: "Titre 1 : dispositions générales (art. 1-6).",
    estimated: false,
  },
  {
    id: "q-const-56", themeId,
    question: "Que couvre le Titre 3 de la Cst. (art. 42-135) ?",
    choices: ["Peuple et cantons", "Confédération, cantons et communes", "Autorités fédérales", "Droits fondamentaux"],
    correctIndex: 1,
    explanation: "Titre 3.",
    estimated: false,
  },
  {
    id: "q-const-57", themeId,
    question: "Que couvre le Titre 4 de la Cst. (art. 136-142) ?",
    choices: ["Peuple et cantons", "Autorités fédérales", "Dispositions générales", "Révision de la Constitution"],
    correctIndex: 0,
    explanation: "Titre 4.",
    estimated: false,
  },
  {
    id: "q-const-58", themeId,
    question: "Que couvre le Titre 6 de la Cst. (art. 192-196) ?",
    choices: ["Droits fondamentaux", "Autorités fédérales", "Peuple et cantons", "Révision de la Constitution et dispositions transitoires"],
    correctIndex: 3,
    explanation: "Titre 6.",
    estimated: false,
  },
  {
    id: "q-const-59", themeId,
    question: "Que couvre le Titre 5 de la Cst. (art. 173-191) ?",
    choices: ["Les droits fondamentaux", "Les cantons", "Les autorités fédérales", "La révision"],
    correctIndex: 2,
    explanation: "Titre 5.",
    estimated: false,
  },
  {
    id: "q-const-60", themeId,
    question: "Quel est un synonyme de « traité international » ?",
    choices: ["Loi fédérale", "Convention internationale", "Concordat", "Ordonnance"],
    correctIndex: 1,
    explanation: "Le cours les nomme aussi conventions internationales.",
    estimated: false,
  },
  {
    id: "q-const-61", themeId,
    question: "Une convention intercantonale est :",
    choices: ["Un accord entre cantons", "Un accord entre États", "Une loi fédérale", "Un jugement"],
    correctIndex: 0,
    explanation: "Similitude au niveau des principes avec les traités internationaux.",
    estimated: false,
  },
  {
    id: "q-const-62", themeId,
    question: "« Primauté du droit international » vient de :",
    choices: ["Art. 190 Cst.", "Art. 36 Cst.", "Art. 10 Cst.", "Art. 5 al. 4 Cst."],
    correctIndex: 3,
    explanation: "La Confédération et les cantons respectent le droit international.",
    estimated: false,
  },
  {
    id: "q-const-63", themeId,
    question: "« Incorporation du droit international » vient de :",
    choices: ["Art. 5 al. 4 Cst.", "Art. 36 Cst.", "Art. 190 Cst.", "Art. 29 Cst."],
    correctIndex: 2,
    explanation: "Le TF et les autres autorités sont tenus d'appliquer les lois fédérales et le droit international.",
    estimated: false,
  },
  {
    id: "q-const-64", themeId,
    question: "Qui est tenu d'appliquer les lois fédérales et le droit international selon l'art. 190 Cst. ?",
    choices: ["Uniquement le Conseil fédéral", "Le Tribunal fédéral et les autres autorités", "Uniquement les cantons", "Les particuliers"],
    correctIndex: 1,
    explanation: "Art. 190 Cst.",
    estimated: false,
  },
  {
    id: "q-const-65", themeId,
    question: "Dans le fédéralisme suisse, qui définit les domaines de compétence ?",
    choices: ["La Constitution", "Le Conseil fédéral", "Les communes", "Le TF"],
    correctIndex: 0,
    explanation: "La Constitution définit les compétences ; les cantons sont souverains sauf limitation.",
    estimated: false,
  },
  {
    id: "q-const-66", themeId,
    question: "Les demi-cantons sont :",
    choices: ["En plus des 26 cantons", "Des communes", "Des États étrangers", "Compris dans les 26 cantons"],
    correctIndex: 3,
    explanation: "26 cantons (dont des demi-cantons).",
    estimated: false,
  },
  {
    id: "q-const-67", themeId,
    question: "Quels sont les trois pouvoirs ?",
    choices: ["Fédéral, cantonal, communal", "Public, privé, mixte", "Législatif, exécutif, judiciaire", "Peuple, cantons, communes"],
    correctIndex: 2,
    explanation: "Séparation des pouvoirs.",
    estimated: false,
  },
  {
    id: "q-const-68", themeId,
    question: "Dans le schéma des pouvoirs, qui « exécute les lois » ?",
    choices: ["Le Parlement", "Le gouvernement (pouvoir exécutif)", "Les tribunaux", "Le peuple"],
    correctIndex: 1,
    explanation: "Le gouvernement exécute les lois ; le Parlement édicte les lois ; les tribunaux veillent à la bonne application.",
    estimated: false,
  },
  {
    id: "q-const-69", themeId,
    question: "Dans le schéma des pouvoirs, qui « édicte les lois » ?",
    choices: ["Le Parlement (pouvoir législatif)", "Le gouvernement", "Les tribunaux", "Le Conseil des États seul"],
    correctIndex: 0,
    explanation: "Le Parlement édicte les lois.",
    estimated: false,
  },
  {
    id: "q-const-70", themeId,
    question: "Dans le schéma des pouvoirs, qui « veille à la bonne application des lois » ?",
    choices: ["Le Parlement", "Le Conseil fédéral", "Le peuple", "Les tribunaux de la Confédération (pouvoir judiciaire)"],
    correctIndex: 3,
    explanation: "Pouvoir judiciaire.",
    estimated: false,
  },
  {
    id: "q-const-71", themeId,
    question: "Quels articles régissent l'Assemblée fédérale ?",
    choices: ["Art. 174 à 187 Cst.", "Art. 7 à 36 Cst.", "Art. 143 à 173 et 179 Cst.", "Art. 1 à 5 Cst."],
    correctIndex: 2,
    explanation: "Pouvoir législatif.",
    estimated: false,
  },
  {
    id: "q-const-72", themeId,
    question: "Quels articles régissent le Conseil fédéral ?",
    choices: ["Art. 143 à 173 Cst.", "Art. 174 à 187 Cst.", "Art. 192 à 196 Cst.", "Art. 7 à 41 Cst."],
    correctIndex: 1,
    explanation: "Pouvoir exécutif.",
    estimated: false,
  },
  {
    id: "q-const-73", themeId,
    question: "Les députés sont :",
    choices: ["Élus par le peuple pour le représenter", "Nommés par le Conseil fédéral", "Tirés au sort", "Élus par le TF"],
    correctIndex: 0,
    explanation: "Pouvoir législatif.",
    estimated: false,
  },
  {
    id: "q-const-74", themeId,
    question: "Le Conseil national est :",
    choices: ["La Chambre des cantons", "La Chambre haute", "Le gouvernement", "La Chambre du peuple"],
    correctIndex: 3,
    explanation: "CN = Chambre du peuple ; CE = Chambre haute / Chambre des cantons.",
    estimated: false,
  },
  {
    id: "q-const-75", themeId,
    question: "Le Conseil des États est aussi appelé :",
    choices: ["Chambre du peuple", "Chambre basse", "Chambre haute (Chambre des cantons)", "Assemblée communale"],
    correctIndex: 2,
    explanation: "CE.",
    estimated: false,
  },
  {
    id: "q-const-76", themeId,
    question: "Le Conseil fédéral fonctionne :",
    choices: ["Par sessions publiques", "De manière permanente, ses débats ne sont pas publics, de manière collégiale", "De manière individuelle", "Uniquement en temps de crise"],
    correctIndex: 1,
    explanation: "Organisation de l'exécutif.",
    estimated: false,
  },
  {
    id: "q-const-77", themeId,
    question: "Combien de temps dure le mandat du Président de la Confédération (selon le cours) ?",
    choices: ["Il est élu pour une année", "4 ans", "2 ans", "7 ans"],
    correctIndex: 0,
    explanation: "Un Président élu pour une année ; conseillers fédéraux élus tous les 4 ans.",
    estimated: false,
  },
  {
    id: "q-const-78", themeId,
    question: "Le scrutin à la proportionnelle et à la majoritaire :",
    choices: ["Sont identiques", "Ne sont utilisés qu'au TF", "Sont des types de tribunaux", "Sont deux modes d'élection distincts (le cours en demande la différence)"],
    correctIndex: 3,
    explanation: "Le cours renvoie à la différence entre scrutin proportionnel et majoritaire (pouvoir législatif).",
    estimated: false,
  },
  {
    id: "q-const-79", themeId,
    question: "Qui est le bénéficiaire des droits fondamentaux ?",
    choices: ["L'État", "Le Parlement", "Les individus", "Les cantons"],
    correctIndex: 2,
    explanation: "Au bénéfice des individus ; dirigés contre l'État.",
    estimated: false,
  },
  {
    id: "q-const-80", themeId,
    question: "Les droits fondamentaux peuvent-ils être limités ?",
    choices: ["Non, jamais", "Oui, à des conditions strictes", "Oui, librement", "Seulement par contrat"],
    correctIndex: 1,
    explanation: "Art. 36 Cst.",
    estimated: false,
  },
  {
    id: "q-const-81", themeId,
    question: "De quoi les droits fondamentaux sont-ils composés ?",
    choices: ["De droits, de libertés, de garanties, voire de buts sociaux", "Uniquement de droits", "Uniquement de sanctions", "De lois et d'ordonnances"],
    correctIndex: 0,
    explanation: "Caractéristiques des droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-const-82", themeId,
    question: "Les droits fondamentaux assurent le respect :",
    choices: ["De la souveraineté des cantons", "Des contrats", "De la propriété uniquement", "De la dignité humaine"],
    correctIndex: 3,
    explanation: "Définition de Le Roy.",
    estimated: false,
  },
  {
    id: "q-const-83", themeId,
    question: "Dans quels art. se trouvent les droits fondamentaux de la Cst. ?",
    choices: ["Art. 1 à 5", "Art. 42 à 135", "Art. 7 à 36", "Art. 143 à 173"],
    correctIndex: 2,
    explanation: "Sources : Cst. fédérale (art. 7 à 36) ; catalogue : art. 7 à 34.",
    estimated: false,
  },
  {
    id: "q-const-84", themeId,
    question: "Que signifie CEDH ?",
    choices: ["Cour européenne de justice", "Convention européenne des droits de l'homme", "Code européen du droit humain", "Conseil européen des droits de l'homme"],
    correctIndex: 1,
    explanation: "Source des droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-const-85", themeId,
    question: "Qu'est-ce que le Pacte ONU II ?",
    choices: ["Le Pacte international relatif aux droits civils et politiques", "Un traité sur le commerce", "Un concordat intercantonal", "Une loi fédérale"],
    correctIndex: 0,
    explanation: "Source des droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-const-86", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["Le droit de vote des étrangers", "Le droit à l'asile", "Le droit de grève illimité", "La garantie de la propriété"],
    correctIndex: 3,
    explanation: "Catalogue : égalité, vie, mariage et famille, opinion, réunion, formation de base, science, langue, propriété, établissement, économique, syndicale, association.",
    estimated: false,
  },
  {
    id: "q-const-87", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["Le droit au logement gratuit", "L'obligation scolaire", "La liberté syndicale", "Le droit de vote à 16 ans"],
    correctIndex: 2,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-88", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["Le droit à la retraite à 60 ans", "Le droit à la formation de base", "Le droit aux vacances", "Le droit à un emploi"],
    correctIndex: 1,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-89", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["La liberté économique", "Le droit à l'impôt zéro", "La liberté de dettes", "Le droit au chômage"],
    correctIndex: 0,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-90", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["Le droit de divorcer sans procédure", "Le droit d'héritage illimité", "Le droit de licencier", "Le droit au mariage et à la famille"],
    correctIndex: 3,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-91", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["Le droit à la langue unique", "La liberté du tarif", "La liberté de la langue", "Le monopole linguistique"],
    correctIndex: 2,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-92", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["La liberté d'évasion", "La liberté d'association", "La liberté de la loi", "La liberté des juges"],
    correctIndex: 1,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-93", themeId,
    question: "Lequel est un droit du catalogue des art. 7 à 34 ?",
    choices: ["La liberté d'établissement", "La liberté d'immigration illimitée", "La liberté d'impôt", "La liberté de brevet"],
    correctIndex: 0,
    explanation: "Catalogue du cours.",
    estimated: false,
  },
  {
    id: "q-const-94", themeId,
    question: "Quelle est la 1re condition de l'art. 36 Cst. ?",
    choices: ["Un intérêt privé", "La proportionnalité", "Le consentement du peuple", "Une base légale"],
    correctIndex: 3,
    explanation: "Al. 1.",
    estimated: false,
  },
  {
    id: "q-const-95", themeId,
    question: "Quelle est la 2e condition de l'art. 36 Cst. ?",
    choices: ["Une base légale", "Le noyau intangible", "Un intérêt public ou la protection d'un droit fondamental d'autrui", "Un référendum"],
    correctIndex: 2,
    explanation: "Al. 2.",
    estimated: false,
  },
  {
    id: "q-const-96", themeId,
    question: "Quelle est la 3e condition de l'art. 36 Cst. ?",
    choices: ["L'intérêt public", "La proportionnalité (au but visé)", "La base légale", "L'essence"],
    correctIndex: 1,
    explanation: "Al. 3.",
    estimated: false,
  },
  {
    id: "q-const-97", themeId,
    question: "Quelle est la 4e condition de l'art. 36 Cst. ?",
    choices: ["L'essence des droits fondamentaux est inviolable", "La base légale", "La proportionnalité", "L'intérêt public"],
    correctIndex: 0,
    explanation: "Al. 4.",
    estimated: false,
  },
  {
    id: "q-const-98", themeId,
    question: "Que sont les cas de danger « sérieux, direct et imminent » à l'art. 36 al. 1 ?",
    choices: ["Des cas interdits", "Des cas de droit privé", "Des cas de compétence cantonale", "Des cas réservés (pas besoin d'une loi)"],
    correctIndex: 3,
    explanation: "Les restrictions graves doivent être prévues par une loi ; les cas de danger sérieux, direct et imminent sont réservés.",
    estimated: false,
  },
  {
    id: "q-const-99", themeId,
    question: "Les restrictions graves d'un droit fondamental doivent être prévues :",
    choices: ["Par une ordonnance communale", "Par une coutume", "Par une loi", "Par un contrat"],
    correctIndex: 2,
    explanation: "Art. 36 al. 1.",
    estimated: false,
  },
  {
    id: "q-const-100", themeId,
    question: "La base légale doit avoir :",
    choices: ["Une origine étrangère", "Un degré de précision suffisant", "Une durée de dix ans", "Un caractère facultatif"],
    correctIndex: 1,
    explanation: "Précision suffisante pour la sécurité et la prévisibilité.",
    estimated: false,
  },
  {
    id: "q-const-101", themeId,
    question: "Pourquoi une base légale formelle ?",
    choices: ["Elle permet le contrôle de la démocratie directe", "Elle supprime les tribunaux", "Elle remplace la Constitution", "Elle limite les cantons"],
    correctIndex: 0,
    explanation: "Exigence de base légale formelle.",
    estimated: false,
  },
  {
    id: "q-const-102", themeId,
    question: "Interdire la publicité le long des autoroutes relève de l'intérêt public de :",
    choices: ["La santé", "La tranquillité", "La culture", "La sécurité"],
    correctIndex: 3,
    explanation: "Exemple du cours.",
    estimated: false,
  },
  {
    id: "q-const-103", themeId,
    question: "Limiter la vente de médicaments en ligne relève de l'intérêt public de :",
    choices: ["La sécurité", "La tranquillité", "La santé", "L'économie"],
    correctIndex: 2,
    explanation: "Exemple du cours.",
    estimated: false,
  },
  {
    id: "q-const-104", themeId,
    question: "Restreindre le parcours d'une manifestation relève de l'intérêt public de :",
    choices: ["La sécurité routière uniquement", "La tranquillité", "La santé", "La culture"],
    correctIndex: 1,
    explanation: "Exemple du cours.",
    estimated: false,
  },
  {
    id: "q-const-105", themeId,
    question: "L'intérêt public est aussi :",
    choices: ["Un principe général de l'activité publique (agir pour le bien des citoyens)", "Un droit fondamental", "Une source du droit", "Un tribunal"],
    correctIndex: 0,
    explanation: "Mais c'est aussi lui qui peut justifier une restriction.",
    estimated: false,
  },
  {
    id: "q-const-106", themeId,
    question: "La proportionnalité exige que l'État :",
    choices: ["Utilise tous les moyens disponibles", "Agisse sans base légale", "Supprime le droit visé", "Se limite au strict nécessaire"],
    correctIndex: 3,
    explanation: "Définition.",
    estimated: false,
  },
  {
    id: "q-const-107", themeId,
    question: "Que protège la liberté personnelle (art. 10 Cst.) ?",
    choices: ["La liberté de presse et d'art", "La propriété", "La vie, l'intégrité physique et psychique, la vie privée et la liberté de mouvement", "Le droit de vote"],
    correctIndex: 2,
    explanation: "Art. 10.",
    estimated: false,
  },
  {
    id: "q-const-108", themeId,
    question: "L'intégrité psychique englobe :",
    choices: ["Le consentement du patient pour une opération", "Mode de vie, loisirs, choix du médecin (manifestations élémentaires de la personne humaine)", "La peine de mort", "La détention préventive"],
    correctIndex: 1,
    explanation: "Le consentement du patient relève de l'intégrité physique.",
    estimated: false,
  },
  {
    id: "q-const-109", themeId,
    question: "Quelle liberté protège la création et l'expression artistiques ?",
    choices: ["La liberté de l'art", "La liberté de la science", "La liberté de la presse", "Le droit de pétition"],
    correctIndex: 0,
    explanation: "Libertés de communication.",
    estimated: false,
  },
  {
    id: "q-const-110", themeId,
    question: "Quelle liberté protège la communication par les médias ?",
    choices: ["La liberté d'opinion et d'expression entre particuliers", "La liberté de la science", "La liberté de réunion", "La liberté de la presse ou des médias"],
    correctIndex: 3,
    explanation: "Opinion = entre particuliers ; presse = communication.",
    estimated: false,
  },
  {
    id: "q-const-111", themeId,
    question: "La liberté d'opinion et d'expression s'exerce :",
    choices: ["Uniquement par les médias", "Uniquement par les chercheurs", "Entre particuliers", "Uniquement par l'art"],
    correctIndex: 2,
    explanation: "Libertés de communication.",
    estimated: false,
  },
  {
    id: "q-const-112", themeId,
    question: "Les libertés de communication protègent :",
    choices: ["La personne en tant qu'être économique", "La personne en tant qu'être social", "L'État", "Les entreprises uniquement"],
    correctIndex: 1,
    explanation: "Art. 16, 17, 20-23, 33.",
    estimated: false,
  },
  {
    id: "q-const-113", themeId,
    question: "Quels articles couvrent les libertés de communication ?",
    choices: ["Art. 16, 17, 20-23 et 33 Cst.", "Art. 10 Cst.", "Art. 36 Cst.", "Art. 5 Cst."],
    correctIndex: 0,
    explanation: "Art. 16, 17, 20-23, 33 Cst.",
    estimated: false,
  },
  {
    id: "q-const-114", themeId,
    question: "Le droit de pétition fait partie :",
    choices: ["De l'art. 36 Cst.", "Du droit pénal", "De l'art. 190 Cst.", "Des libertés de communication (art. 33 Cst.)"],
    correctIndex: 3,
    explanation: "Libertés de communication.",
    estimated: false,
  },
];
