import { QuizQuestion } from "@/models/types";

// ⚠️ CONTENU DÉDUIT (estimated: true) — voir CLAUDE.md avant de modifier.

const themeId = "droit-contrats";

export const quizDroitContrats: QuizQuestion[] = [
  {
    id: "q-ct-01", themeId,
    question: "Un contrat naît, selon l'art. 1 CO, de...",
    choices: ["La signature d'un notaire obligatoire", "L'échange de manifestations de volonté concordantes (offre et acceptation)", "L'enregistrement au registre du commerce", "Le paiement d'un acompte"],
    correctIndex: 1,
    explanation: "L'art. 1 CO pose le principe : un contrat se forme par l'échange de deux manifestations de volonté réciproques et concordantes.",
    estimated: true,
  },
  {
    id: "q-ct-02", themeId,
    question: "En droit suisse, la forme d'un contrat est, par principe...",
    choices: ["Toujours écrite", "Libre, sauf exigence légale contraire", "Toujours notariée", "Toujours orale"],
    correctIndex: 1,
    explanation: "Le principe de la liberté de la forme signifie qu'un contrat oral, écrit ou même par actes concluants est en principe valable, sauf exception légale (ex. vente immobilière).",
    estimated: true,
  },
  {
    id: "q-ct-03", themeId,
    question: "Lequel de ces éléments n'est PAS une condition de validité générale d'un contrat ?",
    choices: ["La capacité de contracter des parties", "Un consentement libre et éclairé", "Un contenu possible et licite", "La présence obligatoire d'un avocat"],
    correctIndex: 3,
    explanation: "La présence d'un avocat n'est jamais une condition de validité ; en revanche, capacité, consentement, et contenu licite/possible en sont bien des conditions.",
    estimated: true,
  },
  {
    id: "q-ct-04", themeId,
    question: "Un vice du consentement (comme le dol) peut avoir pour conséquence...",
    choices: ["Aucune, le contrat reste valable dans tous les cas", "De permettre l'invalidation du contrat par la partie lésée", "D'annuler automatiquement tous les contrats de l'entreprise", "De transformer le contrat en contrat de travail"],
    correctIndex: 1,
    explanation: "Un vice du consentement (erreur essentielle, dol, crainte fondée) donne à la partie lésée le droit d'invalider le contrat selon les art. 23 ss CO.",
    estimated: true,
  },
  {
    id: "q-ct-05", themeId,
    question: "En cas d'inexécution d'un contrat, la partie lésée peut en principe...",
    choices: ["Uniquement dénoncer les faits à la police", "Exiger l'exécution, résoudre le contrat et/ou demander des dommages-intérêts", "Uniquement attendre sans recours", "Uniquement demander la nullité pénale du contrat"],
    correctIndex: 1,
    explanation: "Selon les règles générales (art. 97 ss CO), la partie lésée dispose de plusieurs options combinables selon les cas : exécution, résolution, dommages-intérêts.",
    estimated: true,
  },
  {
    id: "q-ct-06", themeId,
    question: "Une offre de contracter, une fois acceptée, engage en principe...",
    choices: ["Uniquement celui qui l'a acceptée", "Les deux parties", "Uniquement l'auteur de l'offre", "Personne, il faut toujours un écrit"],
    correctIndex: 1,
    explanation: "Dès que l'offre est valablement acceptée, le contrat est formé et engage les deux parties.",
    estimated: true,
  },
  {
    id: "q-ct-07", themeId,
    question: "Une erreur qui porte simplement sur les motifs d'une partie, sans lien objectif reconnaissable pour l'autre partie, permet-elle d'invalider le contrat ?",
    choices: ["Oui, toujours", "Non, en principe ce n'est pas une erreur essentielle au sens de l'art. 24 CO", "Oui, mais seulement pour les contrats écrits", "Cela dépend uniquement du montant en jeu"],
    correctIndex: 1,
    explanation: "Une simple erreur sur les motifs, non reconnaissable de bonne foi par l'autre partie comme un élément essentiel, ne constitue en principe pas une erreur essentielle permettant l'invalidation.",
    estimated: true,
  },
  {
    id: "q-ct-08", themeId,
    question: "Quel texte légal règle principalement le droit des contrats en Suisse ?",
    choices: ["Le Code civil (CC)", "Le Code des obligations (CO)", "Le Code pénal (CP)", "La Constitution fédérale"],
    correctIndex: 1,
    explanation: "Le Code des obligations (CO) contient la partie générale des contrats ainsi que les règles sur les principaux contrats spéciaux.",
    estimated: true,
  },
  {
    id: "q-ct-09", themeId,
    question: "La crainte fondée (art. 29-30 CO) désigne une situation où...",
    choices: ["Une partie a simplement eu peur de manquer une bonne affaire", "Une partie a contracté sous la menace illicite d'un dommage sérieux et imminent", "Une partie n'a pas lu le contrat", "Une partie a mal compris une clause technique"],
    correctIndex: 1,
    explanation: "La crainte fondée suppose une menace illicite, sérieuse et actuelle, qui a déterminé la partie à contracter contre sa volonté réelle.",
    estimated: true,
  },
  {
    id: "q-ct-10", themeId,
    question: "Dans quel cas la forme écrite est-elle exigée par la loi, à titre d'exemple classique ?",
    choices: ["L'achat d'un café", "La vente d'un bien immobilier", "La location d'un vélo pour une heure", "L'achat d'un logiciel en ligne"],
    correctIndex: 1,
    explanation: "La vente d'un immeuble doit revêtir la forme authentique (acte notarié), sous peine de nullité — un exemple classique d'exception au principe de la liberté de la forme.",
    estimated: true,
  },
  {
    id: "q-ct-11", themeId,
    question: "Que signifie « pacta sunt servanda », principe sous-jacent au droit des contrats ?",
    choices: ["Les contrats doivent être écrits", "Les contrats doivent être respectés", "Seuls les contrats notariés sont valables", "Les contrats peuvent être annulés librement"],
    correctIndex: 1,
    explanation: "Ce principe latin signifie que les conventions doivent être respectées : une fois valablement conclu, un contrat lie les parties.",
    estimated: true,
  },
  {
    id: "q-ct-12", themeId,
    question: "Une personne sans l'exercice des droits civils (ex. mineure) peut-elle valablement conclure seule tout type de contrat ?",
    choices: ["Oui, sans aucune limite", "Non, sa capacité de contracter est limitée selon les règles du CC", "Cela dépend uniquement du canton", "Oui, mais seulement pour des montants supérieurs à CHF 1000.-"],
    correctIndex: 1,
    explanation: "La capacité civile (réglée par le CC) conditionne la capacité à contracter valablement ; les personnes mineures ou sous curatelle voient leur capacité limitée selon les cas.",
    estimated: true,
  },
  {
    id: "q-ct-13", themeId,
    question: "Un contrat dont le contenu est objectivement impossible à exécuter dès l'origine est...",
    choices: ["Automatiquement valable et exécutoire", "Nul, en principe, faute d'objet possible", "Simplement suspendu jusqu'à ce qu'il devienne possible", "Transformé automatiquement en donation"],
    correctIndex: 1,
    explanation: "Un contrat dont l'objet est impossible dès l'origine est en principe frappé de nullité, faute de contenu possible.",
    estimated: true,
  },
  {
    id: "q-ct-14", themeId,
    question: "Le dol (art. 28 CO) désigne...",
    choices: ["Une simple négligence", "Une tromperie intentionnelle qui détermine l'autre partie à contracter", "Un retard de livraison", "Une clause contractuelle standard"],
    correctIndex: 1,
    explanation: "Le dol est une tromperie intentionnelle (mensonge, dissimulation) par laquelle une partie amène l'autre à conclure un contrat qu'elle n'aurait pas conclu — ou pas aux mêmes conditions — en connaissance de cause.",
    estimated: true,
  },
  {
    id: "q-ct-15", themeId,
    question: "Résoudre un contrat signifie en général...",
    choices: ["Le modifier légèrement", "Mettre fin au contrat, en principe avec effet rétroactif pour les prestations non encore échangées", "Le renouveler automatiquement", "Le transformer en contrat de travail"],
    correctIndex: 1,
    explanation: "La résolution met fin au contrat et vise, en principe, à remettre les parties dans la situation antérieure pour les prestations non encore exécutées.",
    estimated: true,
  },
];
