import { QuizQuestion } from "@/models/types";

// Contenu réel (estimated: false) — Chapitre 2 "Droit constitutionnel et
// droits fondamentaux" (support de cours PGD IG 26/27).

const themeId = "droit-constitutionnel";

export const quizDroitConstitutionnel: QuizQuestion[] = [
  {
    id: "q-const-01", themeId,
    question: "Quels sont les trois éléments constitutifs de l'État ?",
    choices: ["Population, territoire, souveraineté", "Gouvernement, parlement, tribunaux", "Peuple, cantons, communes", "Constitution, lois, ordonnances"],
    correctIndex: 0,
    explanation: "L'État se compose d'une population, d'un territoire et de la souveraineté (autorité détentrice de la force publique étatique).",
    estimated: false,
  },
  {
    id: "q-const-02", themeId,
    question: "Dans quels articles de la Constitution fédérale est défini l'État moderne suisse ?",
    choices: ["Art. 7 à 36", "Art. 1 à 5", "Art. 143 à 173", "Art. 192 à 196"],
    correctIndex: 1,
    explanation: "Le cours situe l'État moderne suisse aux art. 1 à 5 Cst. (Titre 1, dispositions générales : art. 1-6).",
    estimated: false,
  },
  {
    id: "q-const-03", themeId,
    question: "La Constitution (au sens formel) se distingue d'une loi ordinaire par :",
    choices: ["Son auteur uniquement", "Sa date d'entrée en vigueur", "Son objet, sa portée et sa procédure de confection", "Son absence de sanction"],
    correctIndex: 2,
    explanation: "La Cst. est une loi au sens formel édictée par le pouvoir constituant ; elle se distingue d'une loi ordinaire par son objet, sa portée et sa procédure de confection.",
    estimated: false,
  },
  {
    id: "q-const-04", themeId,
    question: "Parmi les propositions suivantes, laquelle n'est PAS un rôle de la Constitution selon le cours ?",
    choices: ["Loi fondamentale", "Limitation du pouvoir", "Expression de la volonté commune", "Juger les litiges entre particuliers"],
    correctIndex: 3,
    explanation: "Les trois rôles vus en cours sont : loi fondamentale, limitation du pouvoir (séparation des pouvoirs) et expression de la volonté commune (votée par le peuple). Juger relève des tribunaux.",
    estimated: false,
  },
  {
    id: "q-const-05", themeId,
    question: "Le droit constitutionnel est une discipline de :",
    choices: ["Droit privé", "Droit public", "Droit international uniquement", "Droit pénal"],
    correctIndex: 1,
    explanation: "Le droit constitutionnel est une discipline de droit public (relation État-citoyens).",
    estimated: false,
  },
  {
    id: "q-const-06", themeId,
    question: "Quelle est la seule source du droit constitutionnel au sens formel ?",
    choices: ["La loi sur le TF", "Les constitutions cantonales", "La Constitution", "Le droit international"],
    correctIndex: 2,
    explanation: "Au sens formel, la source est la Constitution (le texte). Les lois citées, les constitutions cantonales et le droit international sont des sources au sens matériel.",
    estimated: false,
  },
  {
    id: "q-const-07", themeId,
    question: "Quels sont les trois piliers du droit constitutionnel vus en cours ?",
    choices: ["Loi, coutume, jurisprudence", "Législatif, exécutif, judiciaire", "Fédéralisme, démocratie, droits fondamentaux", "Population, territoire, souveraineté"],
    correctIndex: 2,
    explanation: "Les piliers sont le fédéralisme (structure de l'État), la démocratie (représentative, directe / semi-directe) et les droits fondamentaux.",
    estimated: false,
  },
  {
    id: "q-const-08", themeId,
    question: "La Constitution fédérale de 1999 se compose de combien de titres ?",
    choices: ["Quatre", "Cinq", "Six", "Sept"],
    correctIndex: 2,
    explanation: "Elle comprend six titres, des dispositions générales (art. 1-6) à la révision de la Constitution et dispositions transitoires (art. 192-196).",
    estimated: false,
  },
  {
    id: "q-const-09", themeId,
    question: "Dans quel titre de la Cst. se trouvent les droits fondamentaux, la citoyenneté et les buts sociaux ?",
    choices: ["Titre 1 (art. 1-6)", "Titre 2 (art. 7-41)", "Titre 3 (art. 42-135)", "Titre 5 (art. 173-191)"],
    correctIndex: 1,
    explanation: "Le Titre 2 (art. 7-41) traite des droits fondamentaux, de la citoyenneté et des buts sociaux.",
    estimated: false,
  },
  {
    id: "q-const-10", themeId,
    question: "Dans quel titre de la Cst. se trouvent les autorités fédérales ?",
    choices: ["Titre 5 (art. 173-191)", "Titre 4 (art. 136-142)", "Titre 3 (art. 42-135)", "Titre 6 (art. 192-196)"],
    correctIndex: 0,
    explanation: "Le Titre 5 (art. 173-191) traite des autorités fédérales ; le Titre 4 (art. 136-142) du peuple et des cantons.",
    estimated: false,
  },
  {
    id: "q-const-11", themeId,
    question: "Que prévoit l'art. 5 al. 4 Cst. ?",
    choices: ["Le TF applique les lois fédérales", "La Confédération et les cantons respectent le droit international (primauté)", "Les cantons sont souverains", "Le Conseil fédéral compte 7 membres"],
    correctIndex: 1,
    explanation: "L'art. 5 al. 4 Cst. pose la primauté du droit international : la Confédération et les cantons le respectent.",
    estimated: false,
  },
  {
    id: "q-const-12", themeId,
    question: "Que prévoit l'art. 190 Cst. ?",
    choices: ["Le TF et les autres autorités appliquent les lois fédérales et le droit international (incorporation)", "Les droits fondamentaux sont inviolables", "Les cantons sont des États fédérés", "Le peuple vote la Constitution"],
    correctIndex: 0,
    explanation: "L'art. 190 Cst. oblige le Tribunal fédéral et les autres autorités à appliquer les lois fédérales et le droit international : c'est l'incorporation du droit international.",
    estimated: false,
  },
  {
    id: "q-const-13", themeId,
    question: "Qu'est-ce qu'un traité international ?",
    choices: ["Une loi cantonale", "Un contrat entre deux ou plusieurs sujets de droit international qui créent des règles de droit", "Une décision du Tribunal fédéral", "Un accord entre deux communes"],
    correctIndex: 1,
    explanation: "Un traité international (aussi appelé convention internationale) est un contrat entre sujets de droit international qui créent des règles de droit.",
    estimated: false,
  },
  {
    id: "q-const-14", themeId,
    question: "Combien de cantons (y compris les demi-cantons) compte la Suisse ?",
    choices: ["20", "23", "26", "29"],
    correctIndex: 2,
    explanation: "La Confédération helvétique compte 26 cantons (dont des demi-cantons), qui sont des États fédérés.",
    estimated: false,
  },
  {
    id: "q-const-15", themeId,
    question: "Qui forme le pouvoir constituant suisse ?",
    choices: ["Le Conseil fédéral seul", "Les cantons et le peuple", "Le Tribunal fédéral", "L'Assemblée fédérale seule"],
    correctIndex: 1,
    explanation: "Selon le cours, le pouvoir constituant CH = cantons + peuple.",
    estimated: false,
  },
  {
    id: "q-const-16", themeId,
    question: "Dans un État fédéral comme la Suisse, les cantons sont souverains :",
    choices: ["Dans tous les domaines sans exception", "Uniquement en matière pénale", "Tant que leur compétence n'est pas limitée par la Constitution fédérale", "Jamais"],
    correctIndex: 2,
    explanation: "La Constitution définit les domaines de compétence ; les cantons sont souverains tant que leur compétence n'est pas limitée par la Cst.",
    estimated: false,
  },
  {
    id: "q-const-17", themeId,
    question: "Quels sont les trois niveaux juridiques en Suisse ?",
    choices: ["Fédéral, cantonal, communal", "National, régional, local", "Fédéral, international, communal", "Cantonal, intercantonal, européen"],
    correctIndex: 0,
    explanation: "Le droit se décline en trois niveaux : fédéral, cantonal et communal.",
    estimated: false,
  },
  {
    id: "q-const-18", themeId,
    question: "Quel est le principe de la séparation des pouvoirs ?",
    choices: ["Un seul organe exerce toutes les fonctions de l'État", "Les diverses fonctions de l'État sont dévolues à des organes distincts et indépendants", "Les cantons et la Confédération se partagent le pouvoir judiciaire", "Le peuple exerce seul le pouvoir législatif"],
    correctIndex: 1,
    explanation: "Les fonctions de l'État (législatif, exécutif, judiciaire) doivent être confiées à des organes distincts et indépendants.",
    estimated: false,
  },
  {
    id: "q-const-19", themeId,
    question: "Quel organe exerce le pouvoir législatif au niveau fédéral ?",
    choices: ["Le Conseil fédéral", "Le Tribunal fédéral", "L'Assemblée fédérale", "La Conférence des cantons"],
    correctIndex: 2,
    explanation: "Le pouvoir législatif fédéral est exercé par l'Assemblée fédérale (art. 143 à 173 et 179 Cst.).",
    estimated: false,
  },
  {
    id: "q-const-20", themeId,
    question: "Que signifie « système bicaméral » ?",
    choices: ["Deux Chambres se partagent le même pouvoir, traitent les mêmes affaires et siègent séparément", "Deux gouvernements coexistent", "Il y a deux tribunaux suprêmes", "Le Parlement siège deux fois par an"],
    correctIndex: 0,
    explanation: "L'Assemblée fédérale est bicamérale : Conseil national et Conseil des États partagent le même pouvoir et siègent séparément.",
    estimated: false,
  },
  {
    id: "q-const-21", themeId,
    question: "Quelle Chambre représente les cantons ?",
    choices: ["Le Conseil national", "Le Conseil fédéral", "Le Conseil des États (Chambre haute)", "Le Grand conseil"],
    correctIndex: 2,
    explanation: "Le Conseil national est la Chambre du peuple ; le Conseil des États (Chambre haute) est la Chambre des cantons.",
    estimated: false,
  },
  {
    id: "q-const-22", themeId,
    question: "Comment s'appelle le pouvoir législatif au niveau cantonal et au niveau communal ?",
    choices: ["Conseil d'État / Conseil communal", "Parlement ou Grand conseil / Conseil général ou assemblée communale", "Tribunal cantonal / Tribunal communal", "Conseil national / Conseil général"],
    correctIndex: 1,
    explanation: "Cantonal : Parlement / Grand conseil. Communal : Conseil général ou assemblée communale.",
    estimated: false,
  },
  {
    id: "q-const-23", themeId,
    question: "Combien de conseillers fédéraux compte le Conseil fédéral et pour quelle durée sont-ils élus ?",
    choices: ["5 membres, 6 ans", "7 membres, 4 ans", "9 membres, 4 ans", "7 membres, 1 an"],
    correctIndex: 1,
    explanation: "7 conseillers fédéraux sont élus tous les 4 ans par l'Assemblée fédérale ; le Président est élu pour une année.",
    estimated: false,
  },
  {
    id: "q-const-24", themeId,
    question: "Qui élit les conseillers fédéraux ?",
    choices: ["Le peuple", "Les cantons", "Le Tribunal fédéral", "L'Assemblée fédérale"],
    correctIndex: 3,
    explanation: "Les 7 conseillers fédéraux sont élus par l'Assemblée fédérale.",
    estimated: false,
  },
  {
    id: "q-const-25", themeId,
    question: "Que signifie le principe de collégialité du Conseil fédéral ?",
    choices: ["Chaque conseiller décide seul dans son domaine", "L'autorité exécutive agit collectivement ; ses débats ne sont pas publics", "Les débats sont publics et télévisés", "Le Président tranche seul"],
    correctIndex: 1,
    explanation: "L'exécutif fonctionne de manière permanente, ses débats ne sont pas publics et il agit de manière collégiale.",
    estimated: false,
  },
  {
    id: "q-const-26", themeId,
    question: "Quel est l'organe exécutif au niveau cantonal et communal ?",
    choices: ["Gouvernement / Conseil d'État ; Conseil communal", "Grand conseil ; Conseil général", "Tribunal cantonal ; Tribunal communal", "Conseil des États ; Conseil national"],
    correctIndex: 0,
    explanation: "Cantonal : Gouvernement / Conseil d'État. Communal : Conseil communal.",
    estimated: false,
  },
  {
    id: "q-const-27", themeId,
    question: "Contre qui les droits fondamentaux sont-ils dirigés (destinataire) ?",
    choices: ["Contre les particuliers", "Contre l'État ou une autorité disposant de la puissance publique", "Contre les entreprises uniquement", "Contre les étrangers"],
    correctIndex: 1,
    explanation: "Les individus sont les bénéficiaires ; le destinataire est l'État ou une autorité disposant de la puissance publique, qui doit les respecter.",
    estimated: false,
  },
  {
    id: "q-const-28", themeId,
    question: "Quelles sont les sources des droits fondamentaux citées en cours ?",
    choices: ["Uniquement la Cst. fédérale", "Cst. fédérale, constitutions cantonales, CEDH et Pacte ONU II", "Uniquement le Code civil", "Cst. fédérale et jurisprudence cantonale seulement"],
    correctIndex: 1,
    explanation: "Sources : Constitution fédérale (art. 7 à 36), constitutions cantonales, Convention européenne des droits de l'homme et Pacte international relatif aux droits civils et politiques (Pacte ONU II).",
    estimated: false,
  },
  {
    id: "q-const-29", themeId,
    question: "Quel article de la Cst. fixe les conditions de restriction des droits fondamentaux ?",
    choices: ["Art. 5", "Art. 10", "Art. 36", "Art. 190"],
    correctIndex: 2,
    explanation: "L'art. 36 Cst. (Restriction des droits fondamentaux) fixe 4 conditions très restrictives.",
    estimated: false,
  },
  {
    id: "q-const-30", themeId,
    question: "Quelles sont les 4 conditions de l'art. 36 Cst. ?",
    choices: ["Base légale, intérêt public, proportionnalité, respect de l'essence du droit", "Loi, coutume, jurisprudence, doctrine", "Population, territoire, souveraineté, droit", "Base légale, urgence, gratuité, publicité"],
    correctIndex: 0,
    explanation: "Base légale (al. 1), intérêt public ou protection d'un droit fondamental d'autrui (al. 2), proportionnalité (al. 3) et essence inviolable (al. 4).",
    estimated: false,
  },
  {
    id: "q-const-31", themeId,
    question: "Selon l'art. 36 al. 1 Cst., quelles restrictions doivent être prévues par une loi ?",
    choices: ["Toutes les restrictions, même légères", "Les restrictions graves", "Aucune, une ordonnance suffit toujours", "Seulement celles en temps de guerre"],
    correctIndex: 1,
    explanation: "Toute restriction doit avoir une base légale ; les restrictions graves doivent être prévues par une loi. Les cas de danger sérieux, direct et imminent sont réservés.",
    estimated: false,
  },
  {
    id: "q-const-32", themeId,
    question: "Pourquoi exige-t-on une base légale pour restreindre un droit fondamental ?",
    choices: ["Pour garantir la sécurité et la prévisibilité du droit, l'égalité de traitement et la séparation des pouvoirs", "Pour augmenter les impôts", "Pour accélérer les procès", "Pour éviter l'intervention des tribunaux"],
    correctIndex: 0,
    explanation: "La base légale garantit sécurité et prévisibilité, égalité de traitement et séparation des pouvoirs ; la base légale formelle permet le contrôle de la démocratie directe.",
    estimated: false,
  },
  {
    id: "q-const-33", themeId,
    question: "L'intérêt public qui justifie une restriction vise à maintenir l'ordre public, soit :",
    choices: ["La sécurité, la santé, la tranquillité", "La richesse, la réputation, la tradition", "La langue, la religion, la culture", "Le profit, la concurrence, la croissance"],
    correctIndex: 0,
    explanation: "Sécurité (ex. pas de publicité le long des autoroutes), santé (ex. vente de médicaments en ligne), tranquillité (ex. parcours d'une manifestation).",
    estimated: false,
  },
  {
    id: "q-const-34", themeId,
    question: "Que signifie le principe de proportionnalité ?",
    choices: ["L'État peut utiliser n'importe quel moyen s'il poursuit un intérêt public", "L'État limite la restriction d'un droit fondamental au strict nécessaire", "Les droits fondamentaux sont répartis proportionnellement aux cantons", "L'État doit appliquer le scrutin proportionnel"],
    correctIndex: 1,
    explanation: "La poursuite d'un intérêt public légitime ne permet pas n'importe quel moyen : la restriction doit se limiter au strict nécessaire.",
    estimated: false,
  },
  {
    id: "q-const-35", themeId,
    question: "L'interdiction de la peine de mort est une application de quel droit ?",
    choices: ["Liberté de la presse", "Liberté personnelle (art. 10 Cst.), protection de la vie", "Liberté de réunion", "Garantie de la propriété"],
    correctIndex: 1,
    explanation: "L'art. 10 Cst. protège la vie : la peine de mort est interdite.",
    estimated: false,
  },
  {
    id: "q-const-36", themeId,
    question: "Le consentement du patient pour un acte opératoire relève de :",
    choices: ["L'intégrité physique (art. 10 Cst.)", "La liberté de la science", "La liberté de mouvement", "Le droit de pétition"],
    correctIndex: 0,
    explanation: "Le cours cite le consentement du patient pour un acte opératoire comme exemple de protection de l'intégrité physique.",
    estimated: false,
  },
  {
    id: "q-const-37", themeId,
    question: "La détention préventive est donnée en exemple négatif de quelle liberté ?",
    choices: ["Liberté d'opinion", "Liberté de mouvement (liberté d'aller et de venir)", "Liberté de l'art", "Liberté syndicale"],
    correctIndex: 1,
    explanation: "La liberté de mouvement (art. 10 Cst.) est la liberté d'aller et de venir ; la détention préventive en est l'exemple négatif.",
    estimated: false,
  },
  {
    id: "q-const-38", themeId,
    question: "Que protège la vie privée (art. 10 Cst.) selon le cours ?",
    choices: ["La sphère privée et intime, les relations personnelles et familiales, l'honneur et la réputation", "Uniquement le domicile", "Les biens immobiliers", "Les contrats conclus"],
    correctIndex: 0,
    explanation: "La vie privée couvre la sphère privée et intime, les relations personnelles et familiales, l'honneur et la réputation.",
    estimated: false,
  },
  {
    id: "q-const-39", themeId,
    question: "Quelle liberté de communication protège l'enseignement et la recherche ?",
    choices: ["La liberté de la presse", "La liberté de l'art", "La liberté de la science", "La liberté de réunion"],
    correctIndex: 2,
    explanation: "Liberté de la science = enseignement et recherche ; liberté de l'art = création et expression artistiques ; liberté de la presse ou des médias = communication.",
    estimated: false,
  },
  {
    id: "q-const-40", themeId,
    question: "Parmi les suivantes, laquelle fait partie des libertés de communication (art. 16, 17, 20-23, 33 Cst.) ?",
    choices: ["Le droit de pétition", "La garantie de la propriété", "La liberté économique", "Le droit à la vie"],
    correctIndex: 0,
    explanation: "Les libertés de communication incluent : opinion et expression, presse et médias, science, art, réunion, association et droit de pétition.",
    estimated: false,
  },
  {
    id: "q-const-41", themeId,
    question: "Parmi les suivantes, laquelle est une source du droit constitutionnel au sens matériel ?",
    choices: ["La loi fédérale sur les droits politiques", "Le Code des obligations", "Le règlement communal", "Une ordonnance du Conseil fédéral sur les loyers"],
    correctIndex: 0,
    explanation: "Sources au sens matériel : loi sur les droits politiques, loi sur l'Assemblée fédérale, loi sur l'organisation du gouvernement et de l'administration, loi sur le TF, constitutions cantonales, droit international.",
    estimated: false,
  },
  {
    id: "q-const-42", themeId,
    question: "La Suisse est :",
    choices: ["Un État unitaire", "Un État fédéral (Confédération + cantons)", "Une monarchie", "Une démocratie uniquement représentative"],
    correctIndex: 1,
    explanation: "La CH est un État fédéral, les cantons sont des États fédérés ; la démocratie est représentative et directe / semi-directe.",
    estimated: false,
  },
];
