import { QuizQuestion } from "@/models/types";

// ⚠️ CONTENU DÉDUIT (estimated: true) — voir CLAUDE.md avant de modifier.

const themeId = "droits-fondamentaux";

export const quizDroitsFondamentaux: QuizQuestion[] = [
  {
    id: "q-df-01", themeId,
    question: "Où trouve-t-on principalement les droits fondamentaux en droit suisse ?",
    choices: ["Dans le Code des obligations", "Dans la Constitution fédérale (art. 7-36 Cst.)", "Uniquement dans les lois cantonales", "Dans le Code pénal"],
    correctIndex: 1,
    explanation: "Les droits fondamentaux figurent principalement aux art. 7 à 36 de la Constitution fédérale, complétés par la CEDH.",
    estimated: true,
  },
  {
    id: "q-df-02", themeId,
    question: "Quel article protège la liberté économique ?",
    choices: ["Art. 8 Cst.", "Art. 13 Cst.", "Art. 27 Cst.", "Art. 36 Cst."],
    correctIndex: 2,
    explanation: "L'art. 27 Cst. garantit la liberté économique, notamment le libre choix et le libre exercice d'une activité économique.",
    estimated: true,
  },
  {
    id: "q-df-03", themeId,
    question: "Combien de conditions cumulatives faut-il pour restreindre valablement un droit fondamental ?",
    choices: ["Deux", "Trois", "Quatre", "Aucune, c'est toujours possible"],
    correctIndex: 2,
    explanation: "Quatre conditions cumulatives (art. 36 Cst.) : base légale, intérêt public, proportionnalité, respect du noyau intangible.",
    estimated: true,
  },
  {
    id: "q-df-04", themeId,
    question: "Le principe de proportionnalité exige notamment que la mesure soit...",
    choices: ["La plus sévère possible", "Apte, nécessaire et raisonnable par rapport au but visé", "Approuvée par tous les cantons", "Toujours de durée illimitée"],
    correctIndex: 1,
    explanation: "La proportionnalité impose que la mesure soit apte à atteindre le but, nécessaire (pas de mesure moins incisive suffisante) et raisonnable (rapport but/atteinte).",
    estimated: true,
  },
  {
    id: "q-df-05", themeId,
    question: "Les droits fondamentaux s'appliquent avant tout...",
    choices: ["Entre deux entreprises privées", "Dans la relation entre l'individu et l'État", "Uniquement aux citoyens suisses", "Uniquement en matière pénale"],
    correctIndex: 1,
    explanation: "Les droits fondamentaux protègent d'abord l'individu face à l'État ; entre particuliers, leur influence est indirecte (via l'interprétation du droit privé).",
    estimated: true,
  },
  {
    id: "q-df-06", themeId,
    question: "Que garantit l'art. 8 Cst. ?",
    choices: ["La liberté personnelle", "L'égalité de traitement", "La garantie de la propriété", "La liberté d'expression"],
    correctIndex: 1,
    explanation: "L'art. 8 Cst. consacre le principe d'égalité devant la loi et interdit les discriminations.",
    estimated: true,
  },
  {
    id: "q-df-07", themeId,
    question: "Qu'est-ce que le « noyau intangible » d'un droit fondamental ?",
    choices: ["La partie du droit qui ne peut jamais être restreinte, quelles que soient les circonstances", "La partie la moins importante du droit", "Un droit réservé aux personnes morales", "Un droit qui n'existe qu'en temps de guerre"],
    correctIndex: 0,
    explanation: "Même une restriction par ailleurs justifiée (base légale, intérêt public, proportionnalité) ne peut jamais toucher au contenu essentiel et intangible du droit.",
    estimated: true,
  },
  {
    id: "q-df-08", themeId,
    question: "Une entreprise informatique peut invoquer la liberté économique pour...",
    choices: ["Ne jamais respecter la loi", "Exercer et développer son activité économique librement, dans le cadre légal", "Échapper à toute imposition", "Refuser d'engager des employés"],
    correctIndex: 1,
    explanation: "La liberté économique protège le libre exercice d'une activité économique, mais reste soumise au cadre légal général (droit du travail, fiscal, etc.).",
    estimated: true,
  },
  {
    id: "q-df-09", themeId,
    question: "La CEDH désigne...",
    choices: ["Une loi fédérale suisse", "La Convention européenne des droits de l'homme", "Un tribunal cantonal", "Une ordonnance du Conseil fédéral"],
    correctIndex: 1,
    explanation: "La CEDH est un traité international qui complète, à côté de la Constitution, la protection des droits fondamentaux en Suisse.",
    estimated: true,
  },
  {
    id: "q-df-10", themeId,
    question: "Une restriction sans base légale suffisante est...",
    choices: ["Toujours valable si l'intérêt public est fort", "En principe inadmissible, même si les autres conditions sont remplies", "Valable seulement pour les entreprises", "Sans importance en pratique"],
    correctIndex: 1,
    explanation: "L'exigence d'une base légale est une condition cumulative : son absence rend en principe la restriction inadmissible, même si l'intérêt public existe.",
    estimated: true,
  },
  {
    id: "q-df-11", themeId,
    question: "Que protège l'art. 13 Cst. ?",
    choices: ["La propriété", "La sphère privée (vie privée, correspondance, données)", "La liberté économique", "La liberté de la presse"],
    correctIndex: 1,
    explanation: "L'art. 13 Cst. protège la sphère privée, y compris la correspondance et les relations en télécommunications, ainsi que contre l'emploi abusif de données personnelles.",
    estimated: true,
  },
  {
    id: "q-df-12", themeId,
    question: "L'exigence d'un « intérêt public » signifie que la restriction doit...",
    choices: ["Profiter uniquement à une entreprise privée", "Se justifier par un but d'intérêt général ou la protection des droits d'autrui", "Être décidée par référendum à chaque fois", "N'exister qu'en matière pénale"],
    correctIndex: 1,
    explanation: "La restriction doit répondre à un intérêt public légitime (sécurité, santé, ordre public, etc.) ou à la protection d'un droit fondamental d'un tiers.",
    estimated: true,
  },
  {
    id: "q-df-13", themeId,
    question: "Les restrictions graves à un droit fondamental doivent en principe figurer...",
    choices: ["Dans une simple directive administrative", "Dans une loi au sens formel (votée par le Parlement)", "Dans une note interne", "Nulle part, elles sont interdites de toute façon"],
    correctIndex: 1,
    explanation: "Plus une restriction est grave, plus l'exigence de base légale est stricte : une atteinte grave nécessite en principe une loi au sens formel.",
    estimated: true,
  },
  {
    id: "q-df-14", themeId,
    question: "La garantie de la propriété (art. 26 Cst.) protège...",
    choices: ["Uniquement les biens immobiliers", "Les droits patrimoniaux en général, y compris mobiliers et incorporels", "Uniquement les entreprises publiques", "Uniquement les citoyens suisses"],
    correctIndex: 1,
    explanation: "L'art. 26 Cst. protège la propriété au sens large, incluant les droits patrimoniaux mobiliers et certains droits incorporels.",
    estimated: true,
  },
  {
    id: "q-df-15", themeId,
    question: "Pourquoi étudie-t-on les droits fondamentaux dans un cours orienté informatique ?",
    choices: ["Ce n'est pas pertinent pour ce domaine", "Car des sujets comme la protection des données touchent directement à la sphère privée et à la liberté économique", "Uniquement pour la culture générale", "Parce que seuls les juristes en ont besoin"],
    correctIndex: 1,
    explanation: "Des questions comme la collecte de données, la surveillance ou la liberté d'entreprendre dans le numérique mobilisent directement des droits fondamentaux comme la sphère privée et la liberté économique.",
    estimated: true,
  },
];
