import { QuizQuestion } from "@/models/types";

// ⚠️ CONTENU DÉDUIT (estimated: true) — voir CLAUDE.md avant de modifier.

const themeId = "etat-federalisme";

export const quizEtatFederalisme: QuizQuestion[] = [
  {
    id: "q-etat-01", themeId,
    question: "Le principe d'attribution des compétences signifie que...",
    choices: ["Les cantons n'ont aucune compétence propre", "La Confédération n'a que les compétences que lui attribue la Constitution", "Seule la Confédération légifère", "Les communes décident de tout"],
    correctIndex: 1,
    explanation: "La Confédération agit uniquement dans les domaines que la Constitution lui attribue expressément ; le reste relève des cantons.",
    estimated: true,
  },
  {
    id: "q-etat-02", themeId,
    question: "Combien de cantons compte la Suisse ?",
    choices: ["20", "23", "26", "30"],
    correctIndex: 2,
    explanation: "La Suisse compte 26 cantons.",
    estimated: true,
  },
  {
    id: "q-etat-03", themeId,
    question: "Quel organe exerce le pouvoir exécutif au niveau fédéral ?",
    choices: ["L'Assemblée fédérale", "Le Conseil fédéral", "Le Tribunal fédéral", "Le peuple"],
    correctIndex: 1,
    explanation: "Le Conseil fédéral (avec l'administration fédérale) exerce le pouvoir exécutif : il applique les lois adoptées par le Parlement.",
    estimated: true,
  },
  {
    id: "q-etat-04", themeId,
    question: "Quel est le rôle du pouvoir judiciaire ?",
    choices: ["Faire les lois", "Appliquer les lois au quotidien", "Trancher les litiges en appliquant le droit", "Négocier les traités internationaux"],
    correctIndex: 2,
    explanation: "Le pouvoir judiciaire (tribunaux, dont le Tribunal fédéral) tranche les litiges en interprétant et appliquant le droit à des cas concrets.",
    estimated: true,
  },
  {
    id: "q-etat-05", themeId,
    question: "Pourquoi sépare-t-on les pouvoirs législatif, exécutif et judiciaire ?",
    choices: ["Pour accélérer les décisions", "Pour éviter la concentration du pouvoir entre les mêmes mains", "Parce que la Constitution l'exige pour des raisons historiques uniquement", "Pour réduire les coûts de l'État"],
    correctIndex: 1,
    explanation: "La séparation des pouvoirs vise à empêcher qu'un même organe cumule le pouvoir de faire la loi, de l'appliquer et de juger, ce qui garantit un contrôle mutuel.",
    estimated: true,
  },
  {
    id: "q-etat-06", themeId,
    question: "Le référendum facultatif permet au peuple de...",
    choices: ["Proposer un nouveau texte constitutionnel", "Se prononcer sur une loi déjà adoptée par le Parlement", "Élire le Conseil fédéral", "Modifier une ordonnance"],
    correctIndex: 1,
    explanation: "Le référendum facultatif permet, avec 50 000 signatures dans les 100 jours, de soumettre au vote populaire une loi déjà votée par le Parlement.",
    estimated: true,
  },
  {
    id: "q-etat-07", themeId,
    question: "L'initiative populaire permet de...",
    choices: ["Annuler une loi existante uniquement", "Proposer une modification de la Constitution fédérale", "Dissoudre le Parlement", "Nommer les juges du Tribunal fédéral"],
    correctIndex: 1,
    explanation: "L'initiative populaire permet à des citoyens de proposer eux-mêmes un nouveau texte ou une modification de la Constitution fédérale.",
    estimated: true,
  },
  {
    id: "q-etat-08", themeId,
    question: "Le Conseil national et le Conseil des États forment ensemble...",
    choices: ["Le Conseil fédéral", "L'Assemblée fédérale", "Le Tribunal fédéral", "La Chancellerie fédérale"],
    correctIndex: 1,
    explanation: "L'Assemblée fédérale (le Parlement suisse) est composée de deux chambres : le Conseil national et le Conseil des États.",
    estimated: true,
  },
  {
    id: "q-etat-09", themeId,
    question: "Quel principe permet aux cantons de garder une large autonomie ?",
    choices: ["Le principe de subsidiarité", "Le principe de légalité", "Le principe de proportionnalité", "Le principe de bonne foi"],
    correctIndex: 0,
    explanation: "Le principe de subsidiarité veut que les tâches soient assumées à l'échelon le plus proche du citoyen (commune, canton) sauf si un intérêt supérieur justifie l'intervention fédérale.",
    estimated: true,
  },
  {
    id: "q-etat-10", themeId,
    question: "Une votation sur une modification de la Constitution nécessite...",
    choices: ["Uniquement la majorité du peuple", "Uniquement la majorité des cantons", "La double majorité : peuple ET cantons", "L'accord du Tribunal fédéral"],
    correctIndex: 2,
    explanation: "Une modification constitutionnelle requiert la double majorité : celle du peuple (votes individuels) et celle des cantons (majorité des cantons favorables).",
    estimated: true,
  },
  {
    id: "q-etat-11", themeId,
    question: "Qui représente la Suisse dans les relations internationales ?",
    choices: ["Chaque canton individuellement", "La Confédération", "Les communes", "Le Tribunal fédéral"],
    correctIndex: 1,
    explanation: "La conclusion de traités internationaux et la représentation à l'étranger relèvent de la compétence de la Confédération.",
    estimated: true,
  },
  {
    id: "q-etat-12", themeId,
    question: "Le référendum obligatoire s'applique notamment...",
    choices: ["À toute décision du Conseil fédéral", "Aux modifications de la Constitution fédérale", "Aux ordonnances d'application", "Aux jugements du Tribunal fédéral"],
    correctIndex: 1,
    explanation: "Toute modification de la Constitution fédérale doit obligatoirement être soumise au vote du peuple et des cantons (référendum obligatoire).",
    estimated: true,
  },
  {
    id: "q-etat-13", themeId,
    question: "Qu'est-ce que la démocratie directe, telle que pratiquée en Suisse ?",
    choices: ["Un système où seuls les élus votent les lois", "Un système qui permet au peuple de participer directement par référendum et initiative", "Un système sans Parlement", "Un système propre aux cantons germanophones uniquement"],
    correctIndex: 1,
    explanation: "La démocratie directe donne au peuple des outils (référendum, initiative) pour intervenir directement dans le processus législatif, en complément du système représentatif.",
    estimated: true,
  },
  {
    id: "q-etat-14", themeId,
    question: "Le Tribunal fédéral est...",
    choices: ["Le gouvernement de la Suisse", "La plus haute autorité judiciaire de la Confédération", "Une chambre du Parlement", "Un organe cantonal"],
    correctIndex: 1,
    explanation: "Le Tribunal fédéral est la plus haute juridiction du pays ; il tranche notamment les recours en dernière instance.",
    estimated: true,
  },
  {
    id: "q-etat-15", themeId,
    question: "Pourquoi le fédéralisme peut-il créer des différences de réglementation entre cantons ?",
    choices: ["Parce que la Constitution l'interdit mais que les cantons l'ignorent", "Parce que chaque canton légifère librement dans les domaines qui ne relèvent pas de la Confédération", "Parce que les lois fédérales ne s'appliquent qu'à certains cantons", "Ce n'est pas possible, tout est uniforme en Suisse"],
    correctIndex: 1,
    explanation: "Dans les matières qui restent de leur compétence (école, fiscalité cantonale, police locale, etc.), les cantons légifèrent librement, d'où des différences d'un canton à l'autre.",
    estimated: true,
  },
];
