import { QuizQuestion } from "@/models/types";

// ⚠️ CONTENU DÉDUIT (estimated: true) — voir CLAUDE.md avant de modifier.

const themeId = "protection-personnalite";

export const quizProtectionPersonnalite: QuizQuestion[] = [
  {
    id: "q-pp-01", themeId,
    question: "Quel article du Code civil protège la personnalité ?",
    choices: ["Art. 8 CC", "Art. 28 CC", "Art. 319 CC", "Art. 1 CC"],
    correctIndex: 1,
    explanation: "L'art. 28 CC est la disposition centrale de la protection de la personnalité en droit privé suisse.",
    estimated: true,
  },
  {
    id: "q-pp-02", themeId,
    question: "Une atteinte à la personnalité est, par principe...",
    choices: ["Toujours licite", "Présumée illicite, sauf justification", "Toujours punissable pénalement", "Sans conséquence civile"],
    correctIndex: 1,
    explanation: "L'atteinte à la personnalité est présumée illicite ; c'est à son auteur de démontrer une justification (consentement, intérêt prépondérant, base légale).",
    estimated: true,
  },
  {
    id: "q-pp-03", themeId,
    question: "Laquelle de ces situations peut justifier une atteinte à la personnalité ?",
    choices: ["Le consentement valable de la victime", "La simple volonté de l'auteur", "L'absence de témoins", "Le fait que la victime soit une personne publique, dans tous les cas"],
    correctIndex: 0,
    explanation: "Le consentement de la victime est l'une des justifications classiques, à côté de l'intérêt prépondérant (privé ou public) et d'une base légale.",
    estimated: true,
  },
  {
    id: "q-pp-04", themeId,
    question: "Que peut demander la victime d'une atteinte à sa personnalité selon les art. 28 ss CC ?",
    choices: ["Uniquement des excuses publiques", "La cessation de l'atteinte, son interdiction future, sa constatation et une éventuelle réparation", "Uniquement une sanction pénale", "Rien, seule une plainte pénale est possible"],
    correctIndex: 1,
    explanation: "Les art. 28 ss CC offrent plusieurs actions civiles : cessation, interdiction, constatation de l'illicéité, et réparation (dommages-intérêts, tort moral) selon les cas.",
    estimated: true,
  },
  {
    id: "q-pp-05", themeId,
    question: "Publier la photo identifiable d'une personne sans son accord peut constituer...",
    choices: ["Jamais une atteinte à la personnalité", "Une atteinte potentielle au droit à l'image", "Uniquement une question de droit d'auteur", "Un simple problème de netiquette sans portée juridique"],
    correctIndex: 1,
    explanation: "Le droit à l'image est une composante de la personnalité protégée par l'art. 28 CC ; publier une photo identifiable sans consentement peut y porter atteinte.",
    estimated: true,
  },
  {
    id: "q-pp-06", themeId,
    question: "Quelle loi complète l'art. 28 CC pour les données personnelles ?",
    choices: ["Le Code des obligations", "La loi sur la protection des données (LPD)", "Le Code pénal uniquement", "La loi sur le travail"],
    correctIndex: 1,
    explanation: "La LPD encadre spécifiquement le traitement des données personnelles, en complément de la protection générale offerte par l'art. 28 CC.",
    estimated: true,
  },
  {
    id: "q-pp-07", themeId,
    question: "Un « intérêt prépondérant » peut être...",
    choices: ["Uniquement privé", "Uniquement public", "Privé ou public", "Il n'existe pas en droit suisse"],
    correctIndex: 2,
    explanation: "La justification par intérêt prépondérant peut résulter d'un intérêt privé (ex. légitime défense d'information) ou public (ex. intérêt de la collectivité à être informée).",
    estimated: true,
  },
  {
    id: "q-pp-08", themeId,
    question: "Le « droit à l'oubli » évoqué en lien avec l'art. 28 CC concerne notamment...",
    choices: ["Le droit d'oublier de payer ses dettes", "L'atténuation, avec le temps, de l'intérêt public à la diffusion de faits anciens concernant une personne", "Le droit de supprimer n'importe quel contrat", "Une notion propre au droit pénal uniquement"],
    correctIndex: 1,
    explanation: "Avec l'écoulement du temps, l'intérêt du public à connaître certains faits (ex. une ancienne condamnation) peut s'estomper face à l'intérêt de la personne à sa réinsertion.",
    estimated: true,
  },
  {
    id: "q-pp-09", themeId,
    question: "Qui doit prouver la justification d'une atteinte à la personnalité ?",
    choices: ["La victime de l'atteinte", "L'auteur de l'atteinte", "Le juge d'office, sans preuve nécessaire", "Personne, la preuve n'est jamais nécessaire"],
    correctIndex: 1,
    explanation: "Comme l'atteinte est présumée illicite, c'est à l'auteur de l'atteinte de prouver l'existence d'une justification valable.",
    estimated: true,
  },
  {
    id: "q-pp-10", themeId,
    question: "Diffuser un commentaire diffamatoire sur un collègue peut relever de...",
    choices: ["Uniquement du droit du travail", "D'une atteinte à la personnalité (honneur) au sens de l'art. 28 CC", "D'aucune règle juridique particulière", "Uniquement du droit des contrats"],
    correctIndex: 1,
    explanation: "L'honneur fait partie des biens protégés par la personnalité ; un commentaire diffamatoire peut constituer une atteinte au sens de l'art. 28 CC (en plus d'éventuelles conséquences pénales).",
    estimated: true,
  },
  {
    id: "q-pp-11", themeId,
    question: "L'action en cessation, prévue par les art. 28 ss CC, vise à...",
    choices: ["Obtenir une indemnité financière uniquement", "Faire cesser une atteinte en cours", "Empêcher toute activité future de l'auteur", "Remplacer une procédure pénale"],
    correctIndex: 1,
    explanation: "L'action en cessation permet d'exiger l'arrêt immédiat d'une atteinte à la personnalité qui perdure (ex. retrait d'un contenu en ligne).",
    estimated: true,
  },
  {
    id: "q-pp-12", themeId,
    question: "Une atteinte à la personnalité peut-elle donner lieu à des dommages-intérêts ?",
    choices: ["Jamais", "Oui, si les conditions de la responsabilité civile sont réunies", "Uniquement en cas de faute pénale grave", "Uniquement pour les personnes morales"],
    correctIndex: 1,
    explanation: "Selon les circonstances (préjudice, faute, lien de causalité), la victime peut réclamer des dommages-intérêts, voire une indemnité pour tort moral.",
    estimated: true,
  },
  {
    id: "q-pp-13", themeId,
    question: "Le consentement donné pour la publication d'une photo peut-il être limité ?",
    choices: ["Non, un consentement est toujours total et définitif", "Oui, il peut être limité à un usage, une durée ou un contexte précis", "Non, le consentement n'a aucun effet juridique", "Oui, mais uniquement pour les mineurs"],
    correctIndex: 1,
    explanation: "Le consentement peut être circonscrit (ex. usage sur un site précis, durée limitée) : l'utiliser au-delà de ce cadre peut redevenir une atteinte non justifiée.",
    estimated: true,
  },
  {
    id: "q-pp-14", themeId,
    question: "Une entreprise qui collecte des données de ses utilisateurs sans base légale ni consentement risque...",
    choices: ["Aucun risque juridique", "Une possible atteinte à la personnalité et/ou une violation de la LPD", "Uniquement une sanction fiscale", "Une sanction uniquement si elle est cotée en bourse"],
    correctIndex: 1,
    explanation: "La collecte de données sans base légale ni consentement peut constituer à la fois une atteinte à la personnalité (art. 28 CC) et une violation de la LPD.",
    estimated: true,
  },
  {
    id: "q-pp-15", themeId,
    question: "Quel est le point de départ du raisonnement en matière d'art. 28 CC ?",
    choices: ["Chercher d'abord une sanction pénale", "Identifier s'il y a une atteinte, puis vérifier si elle est justifiée", "Vérifier uniquement si la victime est célèbre", "Se référer uniquement au droit d'auteur"],
    correctIndex: 1,
    explanation: "Le raisonnement classique se fait en deux temps : constater l'existence d'une atteinte, puis examiner si une justification (consentement, intérêt prépondérant, base légale) permet de l'écarter.",
    estimated: true,
  },
];
